export const shipOffers = [
  {
    id: "rook-yard-skiff-miner",
    brand: "Yard Exchange",
    model: "Skiff-M",
    title: "Rook Special Yard Skiff-M",
    price: 20500,
    special: true,
    description: "A cheap working hull with a miner and cargo hold bolted in. Ugly, slow, and legal.",
    hull: 100,
    engine: "Repaired yard engine, tuned for better fuel efficiency",
    includedComponents: ["Engine", "Hull", "Docking", "Scanner", "Miner", "Cargo Hold"],
    tradeoffs: ["Starter mining rig", "Low top speed", "Cheap parts", "Eligible for Rook work"],
  },
  {
    id: "cygnus-utility-mule",
    brand: "Cygnus Dynamics",
    model: "Utility Mule",
    title: "Cygnus Utility Mule",
    price: 68000,
    description: "A dependable boxy hauler with room to grow and a civilized engine.",
    hull: 130,
    engine: "Commercial utility drive",
    includedComponents: ["Engine", "Hull", "Cargo Hold"],
    tradeoffs: ["Strong cargo base", "Slow turn", "No stock miner"],
  },
  {
    id: "novatech-prospector",
    brand: "NovaTech",
    model: "Prospector 3",
    title: "NovaTech Prospector 3",
    price: 94000,
    description: "A real mining starter for buyers who arrive with money instead of optimism.",
    hull: 115,
    engine: "Efficient prospector drive",
    includedComponents: ["Engine", "Hull", "Scanner", "Miner", "Cargo Hold", "Processor"],
    tradeoffs: ["Efficient mining", "Better scanner bay", "Expensive repairs"],
  },
  {
    id: "zenith-dart-runner",
    brand: "Zenith Enterprises",
    model: "Dart Runner",
    title: "Zenith Dart Runner",
    price: 145000,
    description: "Fast, sleek, and wildly inappropriate for a first mining job.",
    hull: 85,
    engine: "High-output dart drive",
    includedComponents: ["Engine", "Hull", "Scanner"],
    tradeoffs: ["Fast ship", "Low cargo", "Fragile hull", "No stock miner"],
  },
];
