import { getNpcName } from "../npcs.js?v=npc-registry-v1";

export const hubServiceDefinitions = {
  "yard-exchange": [
    {
      id: "rook-industries",
      npcId: "rook",
      npcName: getNpcName("rook"),
      organization: "Rook Industries",
      serviceType: "contracts",
      label: "Rook Industries",
      description: "Resource work and starter hauling jobs.",
      contractIds: [
        "rook-red-resource-run-5",
        "rook-red-resource-run-10",
        "rook-blue-resource-run-5",
        "rook-blue-resource-run-10",
      ],
      defaultUnlocked: false,
    },
    {
      id: "yard-shipyard",
      npcId: "barvis",
      npcName: getNpcName("barvis"),
      organization: "Yard Exchange Shipyard",
      serviceType: "shipyard",
      label: "Shipyard",
      description: "Ship sales and refits.",
      defaultUnlocked: false,
    },
    {
      id: "yard-finance",
      npcId: "mako",
      npcName: getNpcName("mako"),
      organization: "Yard Exchange Finance",
      serviceType: "finance",
      label: "Finance",
      description: "Loans and payments.",
      contractIds: ["mako-starter-ship-loan"],
      defaultUnlocked: false,
    },
    {
      id: "yard-supply",
      npcId: "finley",
      npcName: getNpcName("finley"),
      organization: "Yard Exchange Supply",
      serviceType: "supply",
      label: "Supply",
      description: "Repair, fuel, mining charges, scanergy, and basic buying.",
      defaultUnlocked: false,
    },
  ],
  "scrap-porch": [
    {
      id: "scrap-porch-supply",
      npcId: "porch-dispatch",
      npcName: getNpcName("porch-dispatch"),
      organization: "Scrap Porch",
      serviceType: "supply",
      label: "Dispatch Supply",
      description: "Basic repair and refuel service.",
      defaultUnlocked: true,
    },
  ],
};
