import { getNpcName } from "../npcs.js?v=finley-panel-v1";

export const hubServiceDefinitions = {
  "yard-exchange": [
    {
      id: "rook-industries",
      npcId: "rook",
      npcName: getNpcName("rook"),
      organization: "Rook Industries",
      serviceType: "contracts",
      label: "Rook Industries",
      description: "Resource work and starter hauling jobs.",
      contractIds: [
        "rook-red-resource-run-5",
        "rook-red-resource-run-10",
        "rook-blue-resource-run-5",
        "rook-blue-resource-run-10",
      ],
      contractPrerequisites: {
        "rook-red-resource-run-10": ["rook-red-resource-run-5"],
        "rook-blue-resource-run-5": ["rook-red-resource-run-10"],
        "rook-blue-resource-run-10": ["rook-blue-resource-run-5"],
      },
      defaultUnlocked: false,
      greeting: "Got work if you want it. Check what's in the contract tray and let me know.",
      singleActiveContract: true,
      busyMessage: "Got a job out for you already. Finish that one before I put more work on the board.",
    },
    {
      id: "yard-shipyard",
      npcId: "barvis",
      npcName: getNpcName("barvis"),
      organization: "Yard Exchange Shipyard",
      serviceType: "shipyard",
      label: "Shipyard",
      description: "Ship sales and refits.",
      defaultUnlocked: false,
      greeting: "Barvis at the yard window. Take a look at what's on the lot.",
      postSaleGreeting: "She's yours now. Keep the hull clean and the fuel topped. Come back when you're ready to move up.",
    },
    {
      id: "yard-finance",
      npcId: "mako",
      npcName: getNpcName("mako"),
      organization: "Yard Exchange Finance",
      serviceType: "finance",
      label: "Finance",
      description: "Loans and payments.",
      contractIds: ["mako-starter-ship-loan"],
      defaultUnlocked: false,
      greeting: "Mako at Finance. Here to talk terms on something, or check your account?",
    },
    {
      id: "yard-supply",
      npcId: "finley",
      npcName: getNpcName("finley"),
      organization: "Yard Exchange Supply",
      serviceType: "supply",
      label: "Supply",
      description: "Repair, fuel, mining charges, scanergy, and basic buying.",
      defaultUnlocked: false,
      greeting: "Finley at Supply. Need repairs, fuel, or looking to move some cargo?",
      supplyPrices: {
        fuelPerUnit: 2,
        chargePerUnit: 3,
        scanergyPerUnit: 1,
      },
    },
  ],
  "scrap-porch": [
    {
      id: "scrap-porch-supply",
      npcId: "sal",
      npcName: getNpcName("sal"),
      organization: "Scrap Porch Supply",
      serviceType: "supply",
      label: "Supply",
      description: "Basic repair and refuel service.",
      defaultUnlocked: true,
      greeting: "Sal here. What do you need?",
      supplyPrices: {
        fuelPerUnit: 3,
        chargePerUnit: 4,
        scanergyPerUnit: 2,
      },
    },
  ],
};
