import { chapterOneRoute, storySites } from "../storyWorld.js?v=fresh-20260917-1715-cca5018f";

const RESOURCE_CONTRACTS = [
  {
    id: "rook-red-resource-run-5",
    resourceType: "iron-nickel",
    resourceName: "red ore",
    title: "Red Ore Run",
    amount: 5,
    // Rook's lead: the nearest red cluster northeast of the Yard that is not
    // inside Red Teeth (whose edge starts barely 600 units out on that
    // bearing). The first run is meant to stay close to home; the contract
    // used to send a rookie straight at the hunters.
    sourceLead: {
      label: "Rook's red ore lead",
      fromSiteId: storySites.starterHub.id,
      bearing: "northeast",
      maxDistance: 1800,
      avoidZoneIds: ["red-teeth"],
    },
    summary: (dest) => `Deliver 5 red ore to ${dest}. Rook's lead is pinned on your Beacon Locator: red rock northeast of the Yard, short of Red Teeth.`,
  },
  {
    id: "rook-red-resource-run-10",
    resourceType: "iron-nickel",
    resourceName: "red ore",
    title: "Heavy Red Ore Run",
    amount: 10,
    prerequisites: ["rook-red-resource-run-5"],
    sourceLead: {
      label: "Rook's red ore lead",
      fromSiteId: storySites.starterHub.id,
      bearing: "northeast",
      maxDistance: 2400,
    },
    summary: (dest) => `Deliver 10 red ore to ${dest}. The dense belt at the edge of Red Teeth pays better than it looks.`,
  },
  {
    id: "rook-copper-run-5",
    resourceType: "copper",
    resourceName: "copper ore",
    title: "Copper Drift Run",
    amount: 5,
    prerequisites: ["rook-red-resource-run-10"],
    requiresFlightPermitZoneName: "Copper Drift",
    summary: (dest) => `Deliver 5 copper ore to ${dest}. Head northwest into Copper Drift — it's closer than it looks.`,
  },
  {
    id: "rook-copper-run-10",
    resourceType: "copper",
    resourceName: "copper ore",
    title: "Heavy Copper Drift Run",
    amount: 10,
    prerequisites: ["rook-red-resource-run-5"],
    requiresFlightPermitZoneName: "Copper Drift",
    summary: (dest) => `Deliver 10 copper ore to ${dest}. Copper Drift is northwest — teal rocks, medium density field.`,
  },
  {
    id: "rook-red-teeth-claim-run-50",
    resourceType: "iron-nickel",
    resourceName: "red ore",
    title: "Ore Ridge Plot Run",
    amount: 20,
    prerequisites: ["rook-copper-run-10"],
    requiresFlightPermitZoneName: "Ore Ridge",
    sourceClaimIds: [
      "plot-hex-13--9",
      "plot-hex-14--9",
      "plot-hex-13--8",
      "plot-hex-14--8",
      "plot-hex-13--10",
      "plot-hex-14--10",
      "plot-hex-15--10",
      "plot-hex-15--8",
    ],
    sourceClaimLabel: "Ore Ridge charter plot",
    summary: (dest) => `Deliver 20 red ore from Rook's marked Ore Ridge plots to ${dest}. The Beacon Locator can track the plot markers.`,
  },
];

export const chapterOneContracts = [
  {
    id: "rook-yard-exchange-delivery",
    type: "delivery",
    title: "Assessment Delivery",
    issuer: "Rook",
    summary: `Fly the impounded hull from Scrap Porch to ${storySites.starterHub.name} under its own power, for the Authority's assessment.`,
    terms: {
      deliverShipVin: "YRDSKF-01-7A3",
      destinationSiteId: chapterOneRoute.destinationSite.id,
      destinationName: chapterOneRoute.destinationSite.name,
      requirePoweredDown: true,
      requires: [
        { type: "dockAt", siteId: chapterOneRoute.destinationSite.id },
        { type: "shipVinAttached", vin: "YRDSKF-01-7A3" },
        { type: "poweredDown" },
      ],
    },
    reward: {
      // Split: money on signing, the rest on delivery. A hand who starts broke
      // needs the first payment to be something they can watch land on their
      // license, and the balance is what makes finishing the run matter.
      advanceCredits: 250,
      credits: 750,
    },
    clauses: [
      "250 cr advance releases on signing; 750 cr balance on delivery.",
      "Terms are satisfied when the listed VIN docks at the destination hub with ship power down.",
      "Payment releases when the completed contract is confirmed.",
      "Damage penalties are waived for this assessment contract.",
      "Hull released from Yard Exchange Authority impound for this flight only. Arrival under own power completes the Authority's sale assessment.",
    ],
  },
  {
    id: "mako-starter-ship-loan",
    type: "loan",
    title: "Sable Ledger Hull Purchase Note",
    issuer: "Sable Ledger",
    summary: "A purpose-bound loan arranged by Mr. Mako to fund the purchase of one impounded hull. Rook Industries vouches; the pilot alone owes.",
    terms: {
      principal: 20000,
      interestRate: 0.12,
      interestHours: 12,
      maxInterest: 4500,
      dueLabel: "12 in-game hours",
      fundingPurpose: "starter-ship-purchase",
    },
    reward: {
      credits: 20000,
    },
    clauses: [
      "20,000 credits are advanced by Sable Ledger and deposited to the cash account tied to your provisional ID for the hull purchase.",
      "Vouched for by Rook Industries, sponsoring operator. The borrower alone is liable. Sable Ledger does not chase; it collects.",
      "Accepting creates a loan obligation owed to Sable Ledger.",
      "Interest accrues later up to a maximum of 4,500 credits.",
      "If the sale closes, Sable Ledger holds a lien on the hull until the obligation is paid off.",
      "Sale condition: the hull operates under Rook Industries contracts while the lien stands.",
    ],
    considerations: [
      {
        id: "mako-starter-ship-loan-purpose-fulfilled",
        eventType: "ship.purchased",
        once: true,
        setFlag: "purposeFulfilled",
      },
    ],
  },
  {
    id: "authority-impound-hull-sale",
    type: "purchase",
    title: "Authority Impound Sale",
    issuer: "Yard Exchange Authority",
    summary: "Bill of sale for the assessed impound hull currently bearing VIN YRDSKF-01-7A3.",
    terms: {
      deliverShipVin: "YRDSKF-01-7A3",
      price: 20000,
      hullValue: 18500,
      expeditedDispositionFee: 1500,
      destinationName: "Yard Exchange Authority",
    },
    reward: {},
    clauses: [
      "18,500 cr assessed recovery value for the impounded hull.",
      "1,500 cr expedited disposition fee, entered on the Authority schedule and payable with the sale.",
      "Total consideration: 20,000 cr, paid immediately to Yard Exchange Authority.",
      "Title transfers to the pilot on payment. Any lender lien attaches separately under the pilot's financing note.",
      "Sale approved under Rook Industries sponsorship following a successful powered assessment flight.",
    ],
  },
  {
    id: "rook-sponsored-yard-exchange-work-pass",
    type: "permit",
    title: "Rook-Sponsored Yard Exchange Work Pass",
    issuer: "Rook Industries",
    summary: "A sponsored operating pass issued once the pilot holds a ship, a provisional license, and Rook Industries authority.",
    terms: {
      cost: 0,
      permitType: "work-pass",
      authorityId: "yard-exchange-authority",
      grantTerritoryRights: [{ territoryId: "territory:yard-exchange", rights: ["transit", "docking", "mining", "trade"] }],
    },
    reward: {},
    clauses: [
      "No fee. Rook Industries countersigns as sponsoring operator.",
      "Grants standing transit, docking, mining, and trade privileges inside Yard Exchange territory.",
      "Valid while the pilot's provisional license and Rook Industries sponsorship remain in good standing.",
    ],
  },
  {
    id: "mako-emergency-fuel-loan",
    type: "loan",
    repeatable: true,
    title: "Minimum Field Note",
    issuer: "Yard Exchange Finance Office",
    summary: "A standing minimum credit note for pilots who need operating cash.",
    terms: {
      principal: 5000,
      interestRate: 0.18,
      interestHours: 6,
      maxInterest: 1500,
      dueLabel: "6 in-game hours",
      fundingPurpose: "operating-cash",
    },
    reward: {
      credits: 5000,
    },
    clauses: [
      "5,000 credits are deposited to the cash account tied to your provisional ID.",
      "Accepting creates a short field obligation.",
      "This note exists for pilots who made it back alive but not solvent.",
      "Interest accrues later up to a maximum of 1,500 credits.",
      "Use the funds for fuel, repairs, charges, or whatever keeps you moving.",
    ],
  },
  ...RESOURCE_CONTRACTS.map((contract) => ({
    id: contract.id,
    type: "resource-delivery",
    group: "rook-resource-run",
    repeatable: true,
    title: contract.title,
    issuer: "Rook",
    summary: contract.summary ? contract.summary(storySites.starterHub.name) : `Deliver ${contract.amount} ${contract.resourceName} to ${storySites.starterHub.name}.`,
    terms: {
      resourceType: contract.resourceType,
      resourceName: contract.resourceName,
      amount: contract.amount,
      destinationSiteId: storySites.starterHub.id,
      destinationName: storySites.starterHub.name,
      sourceClaimIds: contract.sourceClaimIds ?? [],
      sourceClaimLabel: contract.sourceClaimLabel ?? null,
      sourceLead: contract.sourceLead ?? null,
    },
    reward: {
      creditsPerUnit: 200,
      credits: contract.amount * 200,
    },
    clauses: [
      `Terms are satisfied when ${contract.amount} units of ${contract.resourceName} are delivered from cargo at ${storySites.starterHub.name}.`,
      "Payment releases when the completed contract is confirmed.",
      "Resources must be in the cargo hold, not loose in space.",
      contract.sourceClaimIds?.length
        ? "Only ore traced to the marked contract plots counts for this job. Off-plot ore is marked in cargo."
        : null,
      contract.sourceLead
        ? "The issuer's lead is a best guess pinned on your Beacon Locator, not a claim. Ore from anywhere counts."
        : null,
      "Return to Rook Industries for the next available job.",
    ].filter(Boolean),
  })),
  {
    id: "rtc-copper-drift-flight-permit",
    type: "permit",
    title: "Copper Drift Flight Clearance",
    issuer: "Reach Transit Commission",
    summary: "Extends your provisional flight authorization to cover Copper Drift.",
    terms: {
      cost: 500,
      permitType: "zone-flight",
      zoneId: "copper-drift",
      zoneName: "Copper Drift",
    },
    reward: {},
    clauses: [
      "500 credits, paid immediately from the cash account tied to your provisional ID.",
      "Adds Copper Drift to your authorized flight zones, permanently.",
      "This clears you to fly the zone. Mining rights there are arranged separately with whoever is paying for the job.",
    ],
  },
  {
    id: "rtc-ore-ridge-flight-permit",
    type: "permit",
    title: "Ore Ridge Flight Clearance",
    issuer: "Reach Transit Commission",
    summary: "Extends your provisional flight authorization to cover Ore Ridge.",
    terms: {
      cost: 1200,
      permitType: "zone-flight",
      zoneId: "ore-ridge",
      zoneName: "Ore Ridge",
    },
    reward: {},
    clauses: [
      "1,200 credits, paid immediately from the cash account tied to your provisional ID.",
      "Adds Ore Ridge to your authorized flight zones, permanently.",
      "Ore Ridge sits well outside standard starter routes. Expect denser traffic scrutiny near The Ledge.",
    ],
  },
  {
    id: "rtc-the-ledge-docking-permit",
    type: "permit",
    title: "The Ledge Docking Clearance",
    issuer: "Reach Transit Commission",
    summary: "Pre-clears your ship with The Ledge traffic registry and adds it to Beacon Navigation.",
    terms: {
      cost: 800,
      permitType: "hub-docking",
      siteId: "the-ledge",
      siteName: "The Ledge",
      beaconId: "beacon-the-ledge",
    },
    reward: {},
    clauses: [
      "800 credits, paid immediately from the cash account tied to your provisional ID.",
      "Pre-clears your VIN and pilot license with The Ledge traffic registry — no identity check on first arrival.",
      "Adds The Ledge to Beacon Navigation.",
    ],
  },
  {
    id: "yard-exchange-work-pass",
    type: "permit",
    title: "Yard Exchange Work Pass",
    issuer: "Yard Exchange Authority",
    summary: "Full operating clearance for Yard Exchange's home territory — fly, mine, and haul across the Copper Wake belt.",
    terms: {
      cost: 800,
      permitType: "work-pass",
      authorityId: "yard-exchange-authority",
      grantTerritoryRights: [{ territoryId: "territory:yard-exchange", rights: ["transit", "docking", "mining", "trade"] }],
    },
    reward: {},
    clauses: [
      "800 credits to the Yard Exchange Authority, paid from your provisional account.",
      "Flight clearance for Copper Drift, added to your authorized zones permanently.",
      "Mining rights across Yard Exchange's Copperline claims (the Copper Wake belt).",
      "Covers hauling within the territory. It does not extend past what Yard Exchange controls — Cold Reach and the deep frontier answer to other offices.",
    ],
  },
  {
    id: "yard-copper-wake-mining-lease",
    type: "permit",
    title: "Copper Wake Mining Lease",
    issuer: "Yard Exchange Authority",
    summary: "Copperline (Copper Wake) mining rights on their own, without the full work pass.",
    terms: {
      cost: 500,
      permitType: "mining-rights",
      authorityId: "yard-exchange-authority",
      grantMiningAuthorities: ["copperline-prospectors"],
    },
    reward: {},
    clauses: [
      "500 credits to the Yard Exchange Authority.",
      "Clears you to mine the Copperline claims across the Copper Wake belt.",
      "Flight clearance for the zone is arranged separately if you do not already hold it.",
    ],
  },
  ...[
    ["scrap-porch", "Scrap Porch", "Scrap Porch Commons", 420],
    ["the-ledge", "The Ledge", "Ledge Works Board", 560],
    ["blue-lantern", "Blue Lantern", "Blue Lantern Mutual", 480],
    ["morrow-shoal", "Morrow Shoal", "Morrow Claimholders' Moot", 460],
    ["kiln-crossing", "Kiln Crossing", "Kiln Masters' Chapter", 540],
    ["ore-station-one", "Ore Station One", "Ore Station Syndicate", 650],
    ["coldwater-depot", "Coldwater Depot", "Coldwater Depot Trust", 620],
    ["deep-research", "Deep Research", "Deep Research Collegium", 700],
  ].map(([siteId, siteName, issuer, cost]) => ({
    id: `territory-${siteId}-work-pass`,
    type: "permit",
    title: `${siteName} Work Pass`,
    issuer,
    summary: `Standing transit, docking, trade, and extraction authority within the ${siteName} jurisdiction.`,
    terms: {
      cost,
      permitType: "work-pass",
      authorityId: `${siteId}-authority`,
      grantTerritoryRights: [{ territoryId: `territory:${siteId}`, rights: ["transit", "docking", "mining", "trade"] }],
    },
    reward: {},
    clauses: [
      `${cost} credits paid to ${issuer}.`,
      `Visitor approach remains open without this pass; the pass grants standing commercial and extraction privileges throughout ${siteName}'s controlled territory.`,
      "The grant does not confer patrol, salvage, construction, or enforcement authority.",
    ],
  })),
];
