import { createResponseRecord, evaluateAffordability, generateCapabilityResponses, resolveInstitutionPolicy } from "./institutionDecision.js?v=fresh-20260731-2047-e2997e1";
import { evaluateSupplierAsk } from "./valuation.js?v=fresh-20260731-2047-e2997e1";
import { getResourceTradeValue } from "./resourceDefinitions.js?v=fresh-20260731-2047-e2997e1";
import { PROCUREMENT_STATUS, getProcurementFreightOffers, listOrders } from "./hubProcurement.js?v=fresh-20260731-2047-e2997e1";
import { getServiceCost, getUnitCost, recordAcquisition, recordServiceCost } from "./costBasis.js?v=fresh-20260731-2047-e2997e1";
import { buildPhysicalTransportationRoute, createTransportationNetwork, evaluateTransportPlan, findTransportationRoute } from "./transportationPlanning.js?v=fresh-20260731-2047-e2997e1";
import { FIRST_REACH_CARRIER_POLICY, FIRST_REACH_REPAIR_OPTIONS, FIRST_REACH_TRANSPORT_CONNECTIONS } from "../content/transportation/firstReachNetwork.js?v=fresh-20260731-2047-e2997e1";
import { BLOCKER_KIND, DIAGNOSTIC_STATE, createBlocker, recordBlocker, recordDecision, recordDiagnostic } from "./diagnostics.js?v=fresh-20260731-2047-e2997e1";

// Until a carrier has actually paid for a repair, assume this much for upkeep.
const FREIGHT_REFERENCE_SERVICE_COST = 180;
const FREIGHT_REPRICE_INTERVAL_MS = 45 * 1000;
const FREIGHT_REPRICE_MAX_MULTIPLE = 2.5;
const CARRIER_DEFAULT_TRAITS = Object.freeze({ caution: 0.5, growthBias: 0.3 });

const SITE_NAMES = Object.freeze({
  "yard-exchange": "Yard Exchange",
  "scrap-porch": "Scrap Porch",
  "the-ledge": "The Ledge",
});

// The four authored freight routes that used to live here are gone.
//
// They ran whether or not anyone wanted the cargo: no buyer, no agreed sale, no
// downstream use. Every freight run is now generated by hubProcurement from a
// real purchase order — a buyer short of a family it may not mine, a supplier
// that agreed to sell, and goods that actually exist — so the offer board is
// derived rather than authored. See getProcurementFreightOffers.
//
// Kept as an empty export only so a save written before this still loads.
export const STANDING_FREIGHT_TEMPLATES = Object.freeze([]);

export function createInitialLogisticsState(now = Date.now()) {
  // Hubs open holding a working stock of the family they MINE, and nothing of
  // the families they must import. A settlement that has been feeding a
  // population does not start with an empty warehouse, and starting every hub
  // at zero made all three post critical-urgency mining orders at once and
  // outbid Sal's repair work. Import families stay at zero on purpose: that
  // shortfall is the interdependence, and it is what procurement has to solve.
  return {
    version: 1,
    institutions: {
      "yard-exchange": { id: "yard-exchange", archetypeId: "trade-hub", accounts: { operating: { balance: 5000, committed: 0 } }, inventories: { "iron-nickel": 4, silicate: 0, "water-ice": 0 }, renewableResources: ["iron-nickel"] },
      "scrap-forge": { id: "scrap-forge", archetypeId: "resource-outpost", accounts: { operating: { balance: 3000, committed: 0 } }, inventories: { "water-ice": 6, "iron-nickel": 0, silicate: 0 }, renewableResources: ["water-ice"] },
      "the-ledge": { id: "the-ledge", archetypeId: "frontier-outpost", accounts: { operating: { balance: 4200, committed: 0 } }, inventories: { "iron-nickel": 0, silicate: 4, "water-ice": 0 }, renewableResources: ["silicate"] },
      "carrier:yard-hauler": { id: "carrier:yard-hauler", name: "Quill Independent Freight", referenceId: "FR-CARR-014", archetypeId: "hauling-business", controllerInstitutionId: "person:yard-hauler-operator", accounts: { operating: { id: "FR-ACCT-014", balance: 400, committed: 0, transactions: [] } }, policies: { transportation: { ...FIRST_REACH_CARRIER_POLICY, minimumOperatingCash: 180 } }, repairOptions: FIRST_REACH_REPAIR_OPTIONS.map((entry) => ({ ...entry })) },
      "person:yard-hauler-operator": { id: "person:yard-hauler-operator", name: "Dara Quill", referenceId: "HLC-001-HAULER-YARD-SCRAP", archetypeId: "person", controls: ["carrier:yard-hauler"], license: { id: "HLC-001-HAULER-YARD-SCRAP", class: "commercial-hauler", status: "active" } },
      "ship:hauler-yard-scrap": { id: "ship:hauler-yard-scrap", name: "Yard Hauler", referenceId: "HAUL-01-HAULER-YARD-SCRAP", archetypeId: "cargo-ship", controllerInstitutionId: "carrier:yard-hauler", wear: 0.4, issueCount: 0 },
      "carrier:porch-runner": { id: "carrier:porch-runner", name: "Mara Venn Freight", referenceId: "FR-CARR-022", archetypeId: "hauling-business", controllerInstitutionId: "person:hauler-scrap-yard-operator", accounts: { operating: { id: "FR-ACCT-022", balance: 350, committed: 0, transactions: [] } }, policies: { transportation: { ...FIRST_REACH_CARRIER_POLICY, minimumOperatingCash: 180 } }, repairOptions: FIRST_REACH_REPAIR_OPTIONS.map((entry) => ({ ...entry })) },
      "person:hauler-scrap-yard-operator": { id: "person:hauler-scrap-yard-operator", archetypeId: "person", name: "Mara Venn", referenceId: "HLC-002-HAULER-SCRAP-YARD", controls: ["carrier:porch-runner"], license: { id: "HLC-002-HAULER-SCRAP-YARD", class: "commercial-hauler", status: "active" } },
      "ship:hauler-scrap-yard": { id: "ship:hauler-scrap-yard", name: "Porch Runner Two", referenceId: "HAUL-02-HAULER-SCRAP-YARD", archetypeId: "cargo-ship", controllerInstitutionId: "carrier:porch-runner", wear: 1.8, issueCount: 0 },
    },
    haulers: {
      "hauler-yard-scrap": { shipInstitutionId: "ship:hauler-yard-scrap", carrierInstitutionId: "carrier:yard-hauler", currentSiteId: "yard-exchange", activeShipmentId: null, activeMovementId: null, maintenanceRequested: false, lastDecisionKey: null, status: "seeking-work" },
      "hauler-scrap-yard": { shipInstitutionId: "ship:hauler-scrap-yard", carrierInstitutionId: "carrier:porch-runner", currentSiteId: "scrap-porch", activeShipmentId: null, activeMovementId: null, maintenanceRequested: false, lastDecisionKey: null, status: "seeking-work" },
    },
    shipments: {}, movements: {}, containers: {}, responses: {}, history: [{ id: "log-history-1", type: "logistics.instantiated", at: now }],
    counters: { shipment: 0, movement: 0, container: 0, response: 0, transaction: 0 }, lastLedgerEventId: 0,
  };
}

export function ensureLogisticsState(state, now = Date.now()) {
  state.logistics ??= createInitialLogisticsState(now);
  state.logistics.institutions ??= {};
  state.logistics.institutions["the-ledge"] ??= { id: "the-ledge", archetypeId: "frontier-outpost", accounts: { operating: { balance: 4200, committed: 0 } }, inventories: { "iron-nickel": 0, silicate: 0 }, renewableResources: ["silicate"] };
  ["carrier:yard-hauler", "carrier:porch-runner"].forEach((institutionId) => {
    const institution = state.logistics.institutions?.[institutionId];
    if (!institution) return;
    institution.policies ??= {};
    institution.policies.transportation ??= { ...FIRST_REACH_CARRIER_POLICY };
    institution.repairOptions ??= FIRST_REACH_REPAIR_OPTIONS.map((entry) => ({ ...entry }));
    const identityDefaults = institutionId === "carrier:yard-hauler"
      ? { name: "Quill Independent Freight", referenceId: "FR-CARR-014", accountId: "FR-ACCT-014" }
      : { name: "Mara Venn Freight", referenceId: "FR-CARR-022", accountId: "FR-ACCT-022" };
    institution.name ??= identityDefaults.name;
    institution.referenceId ??= identityDefaults.referenceId;
    institution.accounts.operating.id ??= identityDefaults.accountId;
    institution.accounts.operating.transactions ??= [];
    institution.policies.transportation.minimumOperatingCash ??= 180;
  });
  const personDefaults = {
    "person:yard-hauler-operator": { name: "Dara Quill", referenceId: "HLC-001-HAULER-YARD-SCRAP" },
    "person:hauler-scrap-yard-operator": { name: "Mara Venn", referenceId: "HLC-002-HAULER-SCRAP-YARD" },
  };
  Object.entries(personDefaults).forEach(([institutionId, defaults]) => {
    const institution = state.logistics.institutions[institutionId];
    if (!institution) return;
    institution.name ??= defaults.name; institution.referenceId ??= defaults.referenceId;
    institution.license ??= { id: defaults.referenceId, class: "commercial-hauler", status: "active" };
  });
  state.logistics.movements ??= {};
  state.logistics.counters.movement ??= 0;
  state.logistics.counters.transaction ??= 0;
  Object.values(state.logistics.haulers ?? {}).forEach((hauler) => { hauler.activeMovementId ??= null; hauler.maintenanceRequested ??= false; hauler.lastDecisionKey ??= null; });
  return state.logistics;
}

export function createLogisticsManager({ state, ships = [], destinations = [], now = () => Date.now(), onProcurementDelivered = null, onProcurementShipped = null }) {
  const logistics = ensureLogisticsState(state, now());
  const shipById = new Map(ships.map((ship) => [ship.id, ship]));
  const destinationRecords = destinations.length > 0
    ? destinations
    : Array.from(new Set(FIRST_REACH_TRANSPORT_CONNECTIONS.flatMap((connection) => [connection.fromId, connection.toId]))).map((id) => ({ id }));
  const transportationNetwork = createTransportationNetwork({ destinations: destinationRecords, connections: FIRST_REACH_TRANSPORT_CONNECTIONS });
  for (const [shipId, hauler] of Object.entries(logistics.haulers)) {
    const ship = shipById.get(shipId);
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    if (ship && shipInstitution) { ship.wear = shipInstitution.wear ?? 0; ship.wearIssueCount = shipInstitution.issueCount ?? 0; }
  }

  function update() {
    consumeEvents();
    repriceUnclaimedFreight();
    Object.entries(logistics.haulers).forEach(([shipId, hauler]) => {
      const ship = shipById.get(shipId);
      if (!ship) return;
      const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
      shipInstitution.wear = Math.max(shipInstitution.wear ?? 0, ship.wear ?? 0);
      if (hauler.activeShipmentId && ship.operationalStatus === "seeking-work") {
        const shipment = logistics.shipments[hauler.activeShipmentId];
        if (shipment?.status === "loaded") ship.assignShipment({ shipmentId: shipment.id, destinationSiteId: shipment.destinationSiteId });
      }
      if (!hauler.activeShipmentId && !hauler.activeMovementId && hauler.status === "seeking-work" && ship.operationalStatus !== "maintenance") {
        if (!assignNpcShipment(shipId)) assignMaintenanceAction(shipId);
      }
    });
  }

  function consumeEvents() {
    for (const event of state.ledger.getEventsAfterId(logistics.lastLedgerEventId, { includeHidden: true })) {
      logistics.lastLedgerEventId = Math.max(logistics.lastLedgerEventId, event.id);
      if (event.type === "npc.routeCompleted" && event.payload.shipmentId) {
        if (logistics.shipments[event.payload.shipmentId]) completeNpcShipment(event.payload.npcId, event.payload.shipmentId, event.payload.siteId);
        else if (logistics.movements[event.payload.shipmentId]) completeMaintenanceMovement(event.payload.npcId, event.payload.shipmentId, event.payload.siteId);
      }
      if (event.type === "npc.wearIssue") recordWearIssue(event.payload);
      if (event.type === "sprc.repairCompleted") {
        settleRepairInvoice(event.payload.haulerId, event.payload.serviceRevenue ?? 180, event.payload.repairOrderId);
        restoreAfterMaintenance(event.payload.haulerId);
      }
    }
  }

  // ── Supplier-side freight pricing ────────────────────────────────────────
  // The rate actually on offer for a template: the authored base until an
  // issuer raises it to attract a carrier.
  function getFreightRate(template) {
    logistics.postedFreightRates ??= {};
    return logistics.postedFreightRates[template.id] ?? template.payment;
  }

  // What this run costs the carrier, and therefore what it must be paid.
  // Maintenance is valued at what repairs CURRENTLY cost this carrier, so a
  // repair-price rise flows straight into freight asks.
  function isDueForMaintenance(carrier, shipInstitution) {
    const policy = carrier.policies?.transportation ?? {};
    const threshold = (policy.maximumWear ?? Infinity) - (policy.minimumReturnMargin ?? 0);
    return (shipInstitution?.wear ?? 0) >= threshold;
  }

  function repositionDistance(fromSiteId, toSiteId) {
    if (!fromSiteId || fromSiteId === toSiteId) return 0;
    const route = findTransportationRoute(transportationNetwork, fromSiteId, toSiteId);
    return route?.distance ?? 0;
  }

  function canReposition(fromSiteId, toSiteId) {
    return repositionDistance(fromSiteId, toSiteId) > 0;
  }

  function evaluateCarrierAsk({ template, plan, carrier, currentWear = 0, offeredPrice, repositionFrom = null }) {
    const distance = (plan?.route?.distance ?? 0) + repositionDistance(repositionFrom, template.originSiteId);
    const policy = carrier.policies?.transportation ?? {};
    const serviceCost = getServiceCost(state, carrier.id, "maintenance", FREIGHT_REFERENCE_SERVICE_COST);
    const maxWear = policy.maximumWear ?? 6;
    // Charge only the wear THIS run adds (plan.projectedWear is cumulative and
    // includes the ship's existing wear — billing that to one trip would make
    // every worn carrier refuse all work).
    const incrementalWear = Math.max(0, (plan?.projectedWear ?? currentWear) - currentWear);
    return evaluateSupplierAsk({
      workId: template.id,
      costComponents: {
        travel: distance * (policy.operatingCostPerDistance ?? 0.01),
        // Amortize: this run consumes incrementalWear/maxWear of a service cycle.
        maintenance: maxWear > 0 ? (incrementalWear / maxWear) * serviceCost : 0,
        time: 0,
      },
      offeredPrice,
      traits: logistics.institutions[carrier.controllerInstitutionId]?.traits ?? CARRIER_DEFAULT_TRAITS,
      policy,
    });
  }

  function recordFreightAsk(template, ask) {
    logistics.freightAsks ??= {};
    logistics.freightAsks[template.id] = {
      templateId: template.id,
      ask: ask.recommendedPrice,
      floor: ask.minAcceptablePrice,
      costToServe: Math.round(ask.metrics.costToServe),
      acceptable: ask.acceptable,
      reasons: ask.reasons,
      at: now(),
    };
  }

  // A hub whose freight nobody will carry raises what it pays — bounded,
  // throttled, and logged, mirroring how Sal reprices unfilled purchase orders.
  function repriceUnclaimedFreight() {
    logistics.postedFreightRates ??= {};
    getProcurementFreightOffers(state).forEach((template) => {
      const ask = logistics.freightAsks?.[template.id];
      if (!ask || ask.acceptable) return;
      if (countActiveForTemplate(template.id) > 0) return;
      const lastRepricedAt = logistics.freightRepricedAt?.[template.id] ?? 0;
      if (now() - lastRepricedAt < FREIGHT_REPRICE_INTERVAL_MS) return;

      const current = getFreightRate(template);
      const ceiling = Math.round(template.payment * FREIGHT_REPRICE_MAX_MULTIPLE);
      const next = Math.min(ask.ask, ceiling);
      logistics.freightRepricedAt ??= {};
      logistics.freightRepricedAt[template.id] = now();
      if (next <= current) return;

      const issuer = logistics.institutions[template.issuerInstitutionId];
      const funding = evaluateAffordability({ account: issuer.accounts.operating, policy: { protectedCash: 0 }, cost: next });
      if (!funding.affordable) {
        appendHistory("freight.repriceDeferred", { templateId: template.id, wanted: next, reason: "issuer-cannot-fund" });
        return;
      }
      logistics.postedFreightRates[template.id] = next;
      appendHistory("freight.repriced", { templateId: template.id, previousPayment: current, payment: next, carrierCost: ask.costToServe });
      state.ledger.recordEvent("institution.freightRepriced", {
        institutionId: template.issuerInstitutionId, templateId: template.id, previousPayment: current, payment: next,
        carrierCost: ask.costToServe,
        reasons: [`No carrier would run ${template.originName}→${template.destinationName} at ${current} cr.`, ...ask.reasons],
      }, { visible: true, message: `${siteName(template.destinationSiteId)} raises ${template.commodityName} freight to ${next} cr — carriers cannot cover ${ask.costToServe} cr of cost at ${current}.` });
    });
  }

  // Diagnostics for an idle carrier. The chain matters most here: "no cargo"
  // is usually caused by a source hub being empty, which is caused by whoever
  // was supposed to supply it.
  function publishCarrierDiagnosticBlocker(shipId, hauler, candidates, declined) {
    const context = getCarrierContext(shipId);
    const site = hauler.currentSiteId;
    const localTemplates = getProcurementFreightOffers(state).filter((template) => template.originSiteId === site);
    const outOfStock = localTemplates.filter((template) => (logistics.institutions[template.sourceInstitutionId]?.inventories?.[template.commodity] ?? 0) < template.amount);

    const causes = [];
    // Nothing on the board is now usually caused by a supplier that has agreed
    // to sell and not yet dug the material up. Name it, so the chain continues
    // into that hub's own record rather than stopping at "no cargo".
    if (localTemplates.length === 0) {
      listOrders(state, { status: PROCUREMENT_STATUS.ACCEPTED }).forEach((order) => {
        const held = logistics.institutions[order.supplierInstitutionId]?.inventories?.[order.resourceId] ?? 0;
        causes.push({
          kind: BLOCKER_KIND.SOURCE_OUT_OF_STOCK,
          summary: `${order.supplierInstitutionId} owes ${order.units} ${order.resourceId.replaceAll("-", " ")} on ${order.id} and holds ${held}`,
          subjectId: order.supplierInstitutionId,
          objectId: order.id,
          causedBy: [{ actorId: order.supplierInstitutionId }],
        });
      });
    }
    outOfStock.forEach((template) => {
      // Who is supposed to be filling that shelf? Point at the supplier so the
      // chain continues into their own reasoning.
      const supplierId = state.miningOperation?.institution?.id ?? null;
      causes.push({
        kind: BLOCKER_KIND.SOURCE_OUT_OF_STOCK,
        summary: `${siteName(template.originSiteId)} has no ${template.commodityName} to ship (${template.sourceInstitutionId} holds ${logistics.institutions[template.sourceInstitutionId]?.inventories?.[template.commodity] ?? 0})`,
        subjectId: template.sourceInstitutionId,
        objectId: template.id,
        waitingFor: `${template.commodityName} to arrive in local supply`,
        wakeOn: ["inventory-delivered"],
        causedBy: supplierId ? [{ actorId: supplierId, note: `no ${template.commodityName} has been delivered` }] : [],
        at: now(),
      });
    });
    candidates.filter((candidate) => !candidate.plan.eligible && candidate.plan.reason === "below-carrier-cost").forEach((candidate) => {
      causes.push({
        kind: BLOCKER_KIND.BELOW_COST,
        summary: `${candidate.template.id} pays ${candidate.rate} but costs ${Math.round(candidate.ask?.metrics?.costToServe ?? 0)} to run`,
        subjectId: shipId,
        objectId: candidate.template.id,
        waitingFor: `a rate of at least ${candidate.ask?.minAcceptablePrice ?? "cost"}`,
        wakeOn: ["freight-repriced"],
        at: now(),
      });
    });
    candidates.filter((candidate) => !candidate.plan.eligible && candidate.plan.reason === "payer-cannot-fund").forEach((candidate) => {
      causes.push({
        kind: BLOCKER_KIND.PAYER_CANNOT_FUND,
        summary: `${candidate.template.issuerInstitutionId} cannot fund ${candidate.rate} cr for ${candidate.template.id}`,
        subjectId: candidate.template.issuerInstitutionId,
        objectId: candidate.template.id,
        waitingFor: "the issuer to hold enough cash",
        wakeOn: ["issuer-income"],
        at: now(),
      });
    });

    recordDiagnostic(state, shipId, {
      actorName: context.carrierName ?? shipId,
      actorKind: "ship",
      controllerId: hauler.carrierInstitutionId,
      locationSiteId: site,
      intention: null,
    }, now());
    recordBlocker(state, shipId, createBlocker({
      kind: BLOCKER_KIND.NO_ELIGIBLE_CARGO,
      summary: `${context.pilotName ?? shipId} is docked at ${siteName(site)} with no eligible freight${declined ? ` (${formatReason(declined.plan.reason)})` : ""}`,
      subjectId: shipId,
      objectId: site,
      waitingFor: outOfStock.length ? "cargo to appear in local supply" : "an offer that clears its cost",
      wakeOn: ["inventory-delivered", "freight-repriced", "offer-posted"],
      causedBy: causes,
      detail: { evaluated: candidates.length, declinedReason: declined?.plan.reason ?? "none-offered" },
      at: now(),
    }), { state: DIAGNOSTIC_STATE.WAITING, at: now() });
  }

  function assignNpcShipment(shipId) {
    const hauler = logistics.haulers[shipId];
    const ship = shipById.get(shipId);
    if (!ship) return null;
    if (ship.dockedSiteId !== hauler.currentSiteId) {
      publishDecisionOnce(shipId, `waiting-dock:${hauler.currentSiteId}:${ship.dockedSiteId ?? "none"}`, `${getCarrierContext(shipId).pilotName} is holding outside ${siteName(hauler.currentSiteId)}; a freight contract cannot be accepted until the hauler docks.`, { reason: "not-docked", currentSiteId: hauler.currentSiteId, dockedSiteId: ship.dockedSiteId ?? null });
      return null;
    }
    const carrier = logistics.institutions[hauler.carrierInstitutionId];
    const account = carrier.accounts.operating;
    if (account.balance < 0) {
      publishDecisionOnce(shipId, `insolvent:${account.balance}`, `${getCarrierContext(shipId).carrierName} cannot accept freight: account ${account.id} is overdrawn at ${account.balance} cr.`, { reason: "insolvent", balance: account.balance });
      return null;
    }
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    // Every run on the board is backed by a purchase order whose goods exist.
    const offered = getProcurementFreightOffers(state);
    const hasLoadableLocalWork = offered.some((entry) => entry.originSiteId === hauler.currentSiteId
      && countActiveForTemplate(entry.id) < 1
      && (logistics.institutions[entry.sourceInstitutionId]?.inventories?.[entry.commodity] ?? 0) >= entry.amount);
    const candidates = offered
      .filter((entry) => countActiveForTemplate(entry.id) < 1)
      .filter((entry) => (logistics.institutions[entry.sourceInstitutionId]?.inventories?.[entry.commodity] ?? 0) >= entry.amount)
      // A hauler may take a contract from either end of the relationship: if it
      // is not already at the pickup, it flies there empty first and the cost of
      // that leg is priced into what it will accept.
      .map((template) => ({ template, repositionFrom: template.originSiteId === hauler.currentSiteId ? null : hauler.currentSiteId }))
      // Take what is in front of you. A hauler only flies to the far end of a
      // relationship when there is nothing loadable where it already is, and
      // never when it is due for service — reaching further is for healthy
      // hulls. This is what lets either end of a trade lane be served without
      // changing how a carrier behaves when work is already local.
      .filter(({ template, repositionFrom }) => {
        if (!repositionFrom) return true;
        if (hasLoadableLocalWork || isDueForMaintenance(carrier, shipInstitution)) return false;
        return canReposition(hauler.currentSiteId, template.originSiteId);
      })
      .map(({ template, repositionFrom }) => {
        const rate = getFreightRate(template);
        const plan = evaluateTransportPlan({ network: transportationNetwork, originId: template.originSiteId, destinationId: template.destinationSiteId, payment: rate, currentWear: shipInstitution.wear ?? 0, policy: carrier.policies?.transportation, repairOptions: carrier.repairOptions });
        const issuer = logistics.institutions[template.issuerInstitutionId];
        const funding = evaluateAffordability({ account: issuer.accounts.operating, policy: { protectedCash: 0 }, cost: rate });
        // Supplier-side pricing: the carrier totals what the run costs it —
        // including the maintenance it will owe at CURRENT repair prices — and
        // refuses work that does not clear that cost.
        const ask = evaluateCarrierAsk({ template, plan, carrier, currentWear: shipInstitution.wear ?? 0, offeredPrice: rate, repositionFrom });
        recordFreightAsk(template, ask);
        let resolved = plan;
        if (plan.eligible && !funding.affordable) resolved = { ...plan, eligible: false, reason: "payer-cannot-fund", funding };
        else if (plan.eligible && !ask.acceptable) resolved = { ...plan, eligible: false, reason: "below-carrier-cost", ask };
        return { template, plan: resolved, ask, rate, repositionFrom };
      });
    candidates.filter((candidate) => !candidate.plan.eligible).forEach((candidate) => appendHistory("freight.declined", { shipId, templateId: candidate.template.id, reason: candidate.plan.reason }));
    const selected = candidates.filter((candidate) => candidate.plan.eligible).sort((a, b) => b.plan.score - a.plan.score)[0];
    if (!selected) {
      const declined = candidates.find((candidate) => !candidate.plan.eligible);
      publishCarrierDiagnosticBlocker(shipId, hauler, candidates, declined);
      publishDecisionOnce(shipId, `no-work:${hauler.currentSiteId}:${declined?.plan.reason ?? "none-offered"}`, `${getCarrierContext(shipId).pilotName} is docked at ${siteName(hauler.currentSiteId)} but found no eligible freight${declined ? ` (${formatReason(declined.plan.reason)})` : ""}; checking service needs.`, { reason: declined?.plan.reason ?? "no-offer", currentSiteId: hauler.currentSiteId });
      if (candidates.some((candidate) => candidate.plan.reason === "maintenance-policy")) return assignMaintenanceAction(shipId, { force: true });
      return null;
    }
    const { template, plan } = selected;
    const responseId = `LOG-RSP-${++logistics.counters.response}`;
    const policy = resolveInstitutionPolicy({ institutionPolicy: { protectedCash: 100 } });
    const capability = { id: "transport-freight", canAddress: () => true, propose: () => [{ capabilityId: "transport-freight", action: "accept-shipment", purpose: "earn-operating-revenue", estimatedCost: 0, rationale: `Carry available freight from ${template.originName} to ${template.destinationName}.` }] };
    const proposal = generateCapabilityResponses({ institution: carrier, needs: [{ id: `work:${shipId}`, status: "open", urgency: "routine", purpose: "earn-operating-revenue" }], capabilities: [capability], policy })[0];
    logistics.responses[responseId] = { ...createResponseRecord({ id: responseId, needIds: [`work:${shipId}`], capabilityId: proposal.capabilityId, action: proposal.action, rationale: proposal.rationale, priorityScore: proposal.priorityScore, selectedAt: now() }), status: "active" };
    const shipment = createShipment({ template, assigneeType: "npc", assigneeId: shipId, responseId, plan, repositionFrom: selected.repositionFrom ?? null });
    if (!shipment) {
      logistics.responses[responseId].status = "blocked";
      logistics.responses[responseId].lastOutcome = { type: "execution-route-rejected", at: now() };
      appendHistory("freight.declined", { shipId, templateId: template.id, reason: "execution-route-rejected" });
    } else {
      hauler.lastDecisionKey = null;
      // Diagnostics: committed to a run, with the cost/ask that justified it and
      // the alternatives that lost.
      recordDiagnostic(state, shipId, {
        actorName: getCarrierContext(shipId).carrierName ?? shipId,
        actorKind: "ship",
        controllerId: hauler.carrierInstitutionId,
        state: DIAGNOSTIC_STATE.COMMITTED,
        summary: `Hauling ${template.commodityName} ${template.originName} → ${template.destinationName} for ${shipment.payment} cr`,
        locationSiteId: hauler.currentSiteId,
        intention: { id: shipment.id, kind: "transport", goal: `deliver ${template.commodityName} to ${template.destinationName}`, objectId: template.id, contractId: shipment.contractId ?? null, reserved: { containerId: shipment.containerId } },
        blocker: null,
        waitingFor: null,
        wakeOn: ["shipment-delivered", "breakdown"],
        nextReconsiderAt: null,
        refs: { contractIds: [shipment.contractId].filter(Boolean), targetIds: [template.destinationSiteId], dependencyIds: [shipment.containerId] },
      }, now());
      recordDecision(state, shipId, {
        chosen: { id: template.id, label: `${template.commodityName} → ${template.destinationName}`, score: shipment.payment },
        alternatives: candidates
          .filter((candidate) => candidate.template.id !== template.id)
          .map((candidate) => ({
            id: candidate.template.id,
            label: `${candidate.template.commodityName} → ${candidate.template.destinationName}`,
            score: candidate.rate,
            rejectedBecause: candidate.plan.eligible ? "lower score" : formatReason(candidate.plan.reason),
          })),
        reasons: selected.ask?.reasons ?? [],
        at: now(),
      });
      publishCarrierEvent("carrier.contractAccepted", shipId, { shipmentId: shipment.id, templateId: template.id, payment: shipment.payment, originSiteId: template.originSiteId, destinationSiteId: template.destinationSiteId, projectedWear: plan.projectedWear, carrierCost: Math.round(selected.ask?.metrics?.costToServe ?? 0), carrierAsk: selected.ask?.recommendedPrice ?? null }, `${getCarrierContext(shipId).pilotName} accepted ${shipment.payment} cr freight from ${template.originName} to ${template.destinationName}; account balance is ${account.balance} cr.`);
    }
    return shipment;
  }

  function createShipment({ template, assigneeType, assigneeId, responseId = null, contractId = null, plan = null, repositionFrom = null }) {
    const haulRoute = plan?.route ? buildPhysicalTransportationRoute(transportationNetwork, plan.route) : [];
    // A hauler taking work from the far end flies to the pickup empty first, so
    // its route is the deadhead leg followed by the loaded leg.
    const approach = repositionFrom ? findTransportationRoute(transportationNetwork, repositionFrom, template.originSiteId) : null;
    const approachSites = approach ? buildPhysicalTransportationRoute(transportationNetwork, approach) : [];
    const routeSites = approachSites.length > 1 ? [...approachSites.slice(0, -1), ...haulRoute] : haulRoute;
    const assignedShip = assigneeType === "npc" ? shipById.get(assigneeId) : null;
    if (assigneeType === "npc" && (!assignedShip || (assignedShip.canAcceptRoute ? !assignedShip.canAcceptRoute(routeSites) : routeSites.length < 2))) return null;
    const issuer = logistics.institutions[template.issuerInstitutionId];
    // The posted rate, which may have been raised above the authored base to
    // attract a carrier, is the single price used for funding, commitment, and
    // settlement.
    const rate = getFreightRate(template);
    const affordability = evaluateAffordability({ account: issuer.accounts.operating, policy: { protectedCash: 0 }, cost: rate });
    if (!affordability.affordable) return null;
    const source = logistics.institutions[template.sourceInstitutionId];
    if ((source.inventories[template.commodity] ?? 0) < template.amount) return null;

    // Buy the goods from the seller. The buyer must be able to cover the sale
    // AND the freight, or no shipment is created — an unaffordable trade is
    // withheld rather than half-executed.
    const goods = quoteGoods(template.sourceInstitutionId, template.commodity, template.amount);
    const buyerId = template.destinationInstitutionId;
    const buyerAccount = logistics.institutions[buyerId]?.accounts?.operating ?? {};
    if ((buyerAccount.balance ?? 0) < goods.price + rate) {
      recordBlocker(state, buyerId, createBlocker({
        kind: BLOCKER_KIND.PAYER_CANNOT_AFFORD,
        summary: `${buyerId} cannot buy ${template.amount} ${template.commodityName}: ${goods.price} cr of goods plus ${rate} cr freight exceeds its balance`,
        subjectId: buyerId, objectId: template.id,
        waitingFor: "revenue, or a cheaper supplier",
        wakeOn: ["population.goodsPurchased", "order-repriced"],
        detail: { templateId: template.id, goodsPrice: goods.price, freight: rate, balance: Math.round(buyerAccount.balance ?? 0) },
        at: now(),
      }), { state: DIAGNOSTIC_STATE.WAITING, at: now() });
      return null;
    }

    source.inventories[template.commodity] -= template.amount;
    recordAccountTransaction(buyerId, -goods.price, "goods-purchase", template.id, `Bought ${template.amount} ${template.commodityName} from ${template.sourceInstitutionId}`);
    recordAccountTransaction(template.sourceInstitutionId, goods.price, "goods-sale", template.id, `Sold ${template.amount} ${template.commodityName} to ${buyerId}`);
    state.ledger.recordEvent("logistics.goodsSold", {
      sellerId: template.sourceInstitutionId, buyerId, commodity: template.commodity,
      quantity: template.amount, price: goods.price, unitCost: Math.round(goods.unitCost),
      freight: rate, reasons: goods.valuation.reasons,
    }, { visible: true, message: `${template.sourceInstitutionId} sold ${template.amount} ${template.commodityName} to ${buyerId} for ${goods.price} cr, with ${rate} cr freight on top.` });

    issuer.accounts.operating.committed += rate;
    const id = `SHIP-${String(++logistics.counters.shipment).padStart(4, "0")}`;
    const containerId = `CONT-${String(++logistics.counters.container).padStart(4, "0")}`;
    const container = logistics.containers[containerId] = { id: containerId, shipmentId: id, commodity: template.commodity, quantity: template.amount, ownerInstitutionId: template.sourceInstitutionId, custodianInstitutionId: template.sourceInstitutionId, custody: [{ institutionId: template.sourceInstitutionId, action: "created", siteId: template.originSiteId, at: now() }] };
    const shipment = logistics.shipments[id] = { id, templateId: template.id, contractId, responseId, assigneeType, assigneeId, containerId, originSiteId: template.originSiteId, destinationSiteId: template.destinationSiteId, sourceInstitutionId: template.sourceInstitutionId, destinationInstitutionId: template.destinationInstitutionId, issuerInstitutionId: template.issuerInstitutionId, commodity: template.commodity, quantity: template.amount, payment: rate, committedPayment: rate, basePayment: template.payment, goodsPayment: goods.price, goodsUnitCost: goods.unitCost, procurementOrderId: template.procurementOrderId ?? null, repositionedFrom: repositionFrom ?? null, status: "assigned", createdAt: now(), loadedAt: null };
    appendHistory("shipment.assigned", { shipmentId: id, containerId, assigneeId, commodity: template.commodity });
    if (assigneeType === "npc") {
      loadShipment(shipment);
      if (shipment.procurementOrderId) onProcurementShipped?.(shipment.procurementOrderId, shipment.id);
      const hauler = logistics.haulers[assigneeId];
      hauler.activeShipmentId = id; hauler.status = "transporting";
      assignedShip.assignShipment({ shipmentId: id, destinationSiteId: template.destinationSiteId, route: routeSites });
      publishCarrierEvent("carrier.freightLoaded", assigneeId, { shipmentId: id, commodity: template.commodity, quantity: template.amount, destinationSiteId: template.destinationSiteId }, `${getCarrierContext(assigneeId).shipName} loaded ${template.amount} ${template.commodityName} for ${template.destinationName}.`);
    }
    return shipment;
  }

  function assignMaintenanceAction(shipId, options = {}) {
    const hauler = logistics.haulers[shipId];
    const ship = shipById.get(shipId);
    const carrier = logistics.institutions[hauler.carrierInstitutionId];
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    const policy = carrier.policies?.transportation ?? {};
    const threshold = (policy.maximumWear ?? Infinity) - (policy.minimumReturnMargin ?? 0);
    if (!options.force && (shipInstitution.wear ?? 0) < threshold) return null;
    const repairRoutes = carrier.repairOptions
      .map((option) => ({ option, route: findTransportationRoute(transportationNetwork, hauler.currentSiteId, option.destinationId, policy.knownDestinationIds) }))
      .filter((entry) => entry.route)
      .sort((a, b) => (a.option.priority ?? 0) - (b.option.priority ?? 0) || a.route.distance - b.route.distance);
    const selected = repairRoutes[0];
    if (!selected) { appendHistory("maintenance.blocked", { shipId, reason: "no-reachable-maintenance" }); return null; }
    if (hauler.currentSiteId === selected.option.destinationId) return requestPreventiveMaintenance(shipId);
    const routeSites = selected.route.path.map((id) => transportationNetwork.destinations[id]);
    if (ship.canAcceptRoute ? !ship.canAcceptRoute(routeSites) : routeSites.length < 2) { appendHistory("maintenance.blocked", { shipId, reason: "execution-route-rejected" }); return null; }
    const id = `MOVE-${String(++logistics.counters.movement).padStart(4, "0")}`;
    logistics.movements[id] = { id, type: "service-return", shipId, originSiteId: hauler.currentSiteId, destinationSiteId: selected.option.destinationId, providerInstitutionId: selected.option.institutionId, status: "active", createdAt: now() };
    hauler.activeMovementId = id; hauler.status = "returning-maintenance";
    ship.assignShipment({ shipmentId: id, destinationSiteId: selected.option.destinationId, route: routeSites });
    appendHistory("maintenance.returnStarted", { movementId: id, shipId, destinationSiteId: selected.option.destinationId });
    publishCarrierEvent("carrier.maintenanceReturn", shipId, { movementId: id, destinationSiteId: selected.option.destinationId, wear: shipInstitution.wear ?? 0 }, `${getCarrierContext(shipId).pilotName} declined further freight and is returning ${getCarrierContext(shipId).shipName} to ${siteName(selected.option.destinationId)} for service.`);
    return logistics.movements[id];
  }

  function completeMaintenanceMovement(shipId, movementId, siteId) {
    const movement = logistics.movements[movementId];
    if (!movement || movement.status !== "active" || movement.destinationSiteId !== siteId) return false;
    movement.status = "completed"; movement.completedAt = now();
    const hauler = logistics.haulers[shipId];
    hauler.currentSiteId = siteId; hauler.activeMovementId = null;
    shipById.get(shipId)?.clearShipment();
    appendHistory("maintenance.returnCompleted", { movementId, shipId, siteId });
    publishCarrierEvent("carrier.arrivedForMaintenance", shipId, { movementId, siteId }, `${getCarrierContext(shipId).shipName} arrived at ${siteName(siteId)} and is requesting service.`);
    requestPreventiveMaintenance(shipId);
    return true;
  }

  function requestPreventiveMaintenance(shipId) {
    const hauler = logistics.haulers[shipId];
    if (hauler.maintenanceRequested) return null;
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    hauler.maintenanceRequested = true; hauler.status = "maintenance-required";
    const ship = shipById.get(shipId); if (ship) ship.operationalStatus = "maintenance";
    const maintenancePayload = { npcId: shipId, issueType: "preventive-service", wear: shipInstitution.wear ?? 0, issueCount: shipInstitution.issueCount ?? 0, causedByCarefulMode: false };
    state.ledger.recordEvent("logistics.maintenanceRequired", maintenancePayload, { visible: false });
    publishMaintenanceRequest(shipId, maintenancePayload);
    publishCarrierEvent("carrier.maintenanceRequested", shipId, maintenancePayload, `${getCarrierContext(shipId).pilotName} placed ${getCarrierContext(shipId).shipName} in Scrap Porch's service queue at wear ${(shipInstitution.wear ?? 0).toFixed(2)}.`);
    appendHistory("maintenance.requested", { shipId, issueType: "preventive-service" });
    return true;
  }

  function restoreAfterMaintenance(shipId) {
    const hauler = logistics.haulers[shipId];
    if (!hauler) return;
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    shipInstitution.wear = 0; shipInstitution.issueCount = 0;
    hauler.maintenanceRequested = false; hauler.status = "seeking-work";
    const ship = shipById.get(shipId);
    if (ship) { ship.wear = 0; ship.wearIssueCount = 0; ship.pendingWearIssue = null; ship.operationalStatus = "seeking-work"; }
    appendHistory("maintenance.restored", { shipId });
    publishCarrierEvent("carrier.maintenanceCompleted", shipId, { wear: 0 }, `${getCarrierContext(shipId).shipName} cleared maintenance and returned to freight service.`);
  }

  function completeNpcShipment(shipId, shipmentId, siteId) {
    const shipment = logistics.shipments[shipmentId];
    if (!shipment || shipment.status !== "loaded" || shipment.destinationSiteId !== siteId) return false;
    completeShipment(shipment);
    const hauler = logistics.haulers[shipId];
    hauler.currentSiteId = siteId; hauler.activeShipmentId = null; hauler.status = "seeking-work";
    shipById.get(shipId)?.clearShipment();
    return true;
  }

  function completeShipment(shipment) {
    const container = logistics.containers[shipment.containerId];
    transferCustody(container, shipment.destinationInstitutionId, "unloaded", shipment.destinationSiteId);
    container.ownerInstitutionId = shipment.destinationInstitutionId;
    logistics.institutions[shipment.destinationInstitutionId].inventories[shipment.commodity] = (logistics.institutions[shipment.destinationInstitutionId].inventories[shipment.commodity] ?? 0) + shipment.quantity;
    // Landed cost, not just the sale price: the buyer really paid for the
    // goods and the freight to get them here, and anything built from this
    // material should carry both.
    recordAcquisition(state, {
      institutionId: shipment.destinationInstitutionId, itemId: shipment.commodity,
      units: shipment.quantity, totalCost: (shipment.goodsPayment ?? 0) + (shipment.payment ?? 0),
      source: "freight-purchase", at: now(),
    });
    const issuer = logistics.institutions[shipment.issuerInstitutionId];
    recordAccountTransaction(shipment.issuerInstitutionId, -shipment.payment, "freight-payment", shipment.id, `Paid freight delivery ${shipment.id}`);
    issuer.accounts.operating.committed = Math.max(0, issuer.accounts.operating.committed - shipment.payment);
    shipment.committedPayment = 0; shipment.status = "delivered"; shipment.deliveredAt = now();
    if (shipment.assigneeType === "npc") {
      const carrierId = logistics.haulers[shipment.assigneeId].carrierInstitutionId;
      const transaction = recordAccountTransaction(carrierId, shipment.payment, "freight-income", shipment.id, `Completed freight delivery ${shipment.id}`);
      shipById.get(shipment.assigneeId)?.queueCargoTransfer?.({ commodity: shipment.commodity, direction: "to-hub" });
      publishCarrierEvent("carrier.contractFulfilled", shipment.assigneeId, { shipmentId: shipment.id, payment: shipment.payment, transactionId: transaction.id, balance: transaction.balance, destinationSiteId: shipment.destinationSiteId }, `${getCarrierContext(shipment.assigneeId).pilotName} delivered ${shipment.commodity} to ${siteName(shipment.destinationSiteId)}, earned ${shipment.payment} cr, and now has ${transaction.balance} cr.`);
    }
    // A procurement-backed run closes the order that caused it, which is what
    // reduces the buyer's real need rather than just moving material about.
    if (shipment.procurementOrderId) {
      onProcurementDelivered?.(shipment.procurementOrderId, {
        deliveredUnits: shipment.quantity,
        goodsPayment: shipment.goodsPayment ?? 0,
        freightPaid: shipment.payment ?? 0,
      });
    }
    appendHistory("shipment.delivered", { shipmentId: shipment.id, containerId: container.id, payment: shipment.payment });
  }

  function acceptPlayerContract(contract, playerInstitutionId) {
    const template = getProcurementFreightOffers(state).find((entry) => entry.id === contract.terms.standingFreightTemplateId);
    if (!template || countActiveForTemplate(template.id) >= 2) return null;
    return createShipment({ template, assigneeType: "player", assigneeId: playerInstitutionId, contractId: contract.id });
  }

  function loadPlayerContract(contractId) {
    const shipment = Object.values(logistics.shipments).find((entry) => entry.contractId === contractId && entry.status === "assigned");
    return shipment ? loadShipment(shipment) : false;
  }

  function deliverPlayerContract(contractId) {
    const shipment = Object.values(logistics.shipments).find((entry) => entry.contractId === contractId && entry.status === "loaded");
    if (!shipment) return false;
    completeShipment(shipment);
    return true;
  }

  function loadShipment(shipment) {
    if (shipment.status !== "assigned") return false;
    const custodianId = shipment.assigneeType === "npc" ? logistics.haulers[shipment.assigneeId].carrierInstitutionId : shipment.assigneeId;
    transferCustody(logistics.containers[shipment.containerId], custodianId, "loaded", shipment.originSiteId);
    if (shipment.assigneeType === "npc") shipById.get(shipment.assigneeId)?.queueCargoTransfer?.({ commodity: shipment.commodity, direction: "from-hub" });
    shipment.status = "loaded"; shipment.loadedAt = now();
    appendHistory("shipment.loaded", { shipmentId: shipment.id, containerId: shipment.containerId, assigneeId: shipment.assigneeId });
    return true;
  }

  function recordWearIssue(payload) {
    const hauler = logistics.haulers[payload.npcId];
    if (!hauler) return;
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    shipInstitution.wear = payload.wear; shipInstitution.issueCount = payload.issueCount;
    hauler.maintenanceRequested = true; hauler.status = "maintenance-required";
    shipById.get(payload.npcId).operationalStatus = "maintenance";
    appendHistory("ship.issue", payload);
    state.ledger.recordEvent("logistics.maintenanceRequired", payload, { visible: false });
    publishMaintenanceRequest(payload.npcId, payload);
    publishCarrierEvent("carrier.breakdown", payload.npcId, payload, `${getCarrierContext(payload.npcId).shipName} suffered a ${formatReason(payload.issueType ?? "wear issue")} at wear ${(payload.wear ?? 0).toFixed(2)}; ${getCarrierContext(payload.npcId).pilotName} is seeking repair.`);
  }

  function publishMaintenanceRequest(shipId, payload) {
    const hauler = logistics.haulers[shipId];
    const carrier = logistics.institutions[hauler.carrierInstitutionId];
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    const requiredCapabilities = payload.issueType === "hull-fatigue" ? ["structural-repair"] : payload.issueType === "control-fault" ? ["control-systems"] : ["mechanical-repair"];
    state.ledger.recordEvent("maintenance.requested", { subjectId: shipId, subjectName: shipInstitution.name, referenceId: shipInstitution.referenceId, craftClass: "freight-hauler", issueType: payload.issueType, requiredCapabilities, locationSiteId: "scrap-porch", mobility: "recovered", payerInstitutionId: carrier.id, payer: { balance: carrier.accounts.operating.balance, committed: carrier.accounts.operating.committed ?? 0, protectedCash: carrier.policies?.transportation?.minimumOperatingCash ?? 0 }, servicePrice: 180, wear: payload.wear, issueCount: payload.issueCount, causedByCarefulMode: payload.causedByCarefulMode }, { visible: false });
  }

  function settleRepairInvoice(shipId, amount, referenceId) {
    const hauler = logistics.haulers[shipId];
    if (!hauler || !Number.isFinite(amount) || amount <= 0) return null;
    const transaction = recordAccountTransaction(hauler.carrierInstitutionId, -amount, "repair-expense", referenceId, `Paid Scrap Porch repair invoice ${referenceId}`);
    state.sprc.account.balance += amount;
    // Book the real upkeep cost so this carrier's future freight asks reflect
    // what maintenance now costs it.
    recordServiceCost(state, { institutionId: hauler.carrierInstitutionId, serviceType: "maintenance", price: amount, at: now() });
    publishCarrierEvent("carrier.repairPaid", shipId, { repairOrderId: referenceId, amount, transactionId: transaction.id, balance: transaction.balance }, `${getCarrierContext(shipId).carrierName} paid Scrap Porch ${amount} cr for repairs; operating balance is ${transaction.balance} cr.`);
    return transaction;
  }

  // What the supplying institution charges for the GOODS. Freight is a separate
  // payment to the carrier; this is the sale itself, which previously never
  // happened at all — a source hub simply lost material for nothing.
  //
  // The ask is built from what the material actually cost the seller, so the
  // cost basis recorded when it bought ore propagates into what it resells for.
  function quoteGoods(sellerInstitutionId, commodity, quantity) {
    // Floored at plain market worth. A seller that has not recorded a cost
    // basis yet would otherwise part with material for a single credit.
    const marketUnitValue = getResourceTradeValue(commodity);
    const unitCost = Math.max(getUnitCost(state, sellerInstitutionId, commodity) || 0, marketUnitValue);
    const ask = evaluateSupplierAsk({
      workId: `${quantity} ${commodity}`,
      costComponents: { other: unitCost * quantity },
      traits: { growthBias: 0.3, caution: 0.5 },
    });
    return { price: ask.recommendedPrice, unitCost, marketUnitValue, valuation: ask };
  }

  function recordAccountTransaction(institutionId, amount, type, referenceId, description) {
    const institution = logistics.institutions[institutionId];
    institution.accounts ??= {};
    institution.accounts.operating ??= { balance: 0, committed: 0 };
    const account = institution.accounts.operating;
    account.transactions ??= [];
    account.balance = (account.balance ?? 0) + amount;
    const transaction = { id: `TX-${String(++logistics.counters.transaction).padStart(5, "0")}`, at: now(), accountId: account.id ?? `${institutionId}:operating`, institutionId, type, amount, balance: account.balance, referenceId, description };
    account.transactions.push(transaction);
    if (account.transactions.length > 50) account.transactions.splice(0, account.transactions.length - 50);
    return transaction;
  }

  function getCarrierContext(shipId) {
    const hauler = logistics.haulers[shipId] ?? {};
    const carrier = logistics.institutions[hauler.carrierInstitutionId] ?? {};
    const person = logistics.institutions[carrier.controllerInstitutionId] ?? {};
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId] ?? {};
    return { carrierInstitutionId: carrier.id, carrierName: carrier.name ?? carrier.id ?? "Unknown carrier", carrierReferenceId: carrier.referenceId, accountId: carrier.accounts?.operating?.id, pilotInstitutionId: person.id, pilotName: person.name ?? shipId, licenseId: person.license?.id ?? person.referenceId, shipInstitutionId: shipInstitution.id, shipName: shipInstitution.name ?? shipId, shipReferenceId: shipInstitution.referenceId };
  }

  function publishCarrierEvent(type, shipId, payload, message) {
    state.ledger.recordEvent(type, { ...getCarrierContext(shipId), ...payload }, { visible: true, message });
  }

  function publishDecisionOnce(shipId, key, message, payload = {}) {
    const hauler = logistics.haulers[shipId];
    if (!hauler || hauler.lastDecisionKey === key) return;
    hauler.lastDecisionKey = key;
    publishCarrierEvent("carrier.decision", shipId, payload, message);
  }

  function siteName(siteId) { return transportationNetwork.destinations[siteId]?.name ?? SITE_NAMES[siteId] ?? siteId; }
  function formatReason(value) { return String(value).replaceAll("-", " "); }

  function transferCustody(container, institutionId, action, siteId) { container.custodianInstitutionId = institutionId; container.custody.push({ institutionId, action, siteId, at: now() }); }
  function countActiveForTemplate(templateId) { return Object.values(logistics.shipments).filter((entry) => entry.templateId === templateId && ["assigned", "loaded"].includes(entry.status)).length; }
  function appendHistory(type, payload) { logistics.history.push({ id: `log-history-${logistics.history.length + 1}`, type, at: now(), ...payload }); }
  return { update, assignNpcShipment, acceptPlayerContract, loadPlayerContract, deliverPlayerContract, getState: () => logistics };
}

export function createStandingFreightJob(template, issuer = null) {
  return { id: `player-${template.id}`, type: "cargo-run", group: "standing-freight", jobKind: "logistics", repeatable: true, jobTier: "standing", jobTierLabel: "Standing Freight", title: `${template.commodityName} to ${template.destinationName}`, issuer: issuer ?? template.originName, summary: `Load one sealed ${template.commodityName} container at ${template.originName} and deliver it to ${template.destinationName}.`, terms: { commodity: template.commodity, commodityName: template.commodityName, amount: template.amount, originSiteId: template.originSiteId, originName: template.originName, destinationSiteId: template.destinationSiteId, destinationName: template.destinationName, standingFreightTemplateId: template.id }, reward: { credits: template.payment }, clauses: ["This is a standing regional freight offer shared with independent and institutional carriers.", "One real container is assigned on acceptance; custody and inventory transfer are recorded.", "Load at origin and unload at destination."], };
}

// The player sees the same board the carriers do: real runs, backed by real
// purchase orders, and nothing at all where no hub has asked for anything.
export function getStandingFreightJobsForSite(siteId, issuer = null, state = null) {
  if (!state) return [];
  return getProcurementFreightOffers(state)
    .filter((template) => template.originSiteId === siteId)
    .map((template) => createStandingFreightJob(template, issuer));
}
