import { createResponseRecord, evaluateAffordability, generateCapabilityResponses, resolveInstitutionPolicy } from "./institutionDecision.js?v=fresh-20260801-2349-e938384";
import { evaluateSupplierAsk } from "./valuation.js?v=fresh-20260801-2349-e938384";
import { getResourceTradeValue } from "./resourceDefinitions.js?v=fresh-20260801-2349-e938384";
import { PROCUREMENT_STATUS, getProcurementFreightOffers, listOrders } from "./hubProcurement.js?v=fresh-20260801-2349-e938384";
import { getServiceCost, getUnitCost, recordAcquisition, recordServiceCost } from "./costBasis.js?v=fresh-20260801-2349-e938384";
import { getActorTraits } from "./actorConfig.js?v=fresh-20260801-2349-e938384";
import { adaptShipment } from "./intentions.js?v=fresh-20260801-2349-e938384";
import { buildPhysicalTransportationRoute, createTransportationNetwork, evaluateTransportPlan, findTransportationRoute } from "./transportationPlanning.js?v=fresh-20260801-2349-e938384";
import { FIRST_REACH_TRANSPORT_CONNECTIONS } from "../content/transportation/firstReachNetwork.js?v=fresh-20260801-2349-e938384";
import { BLOCKER_KIND, DIAGNOSTIC_STATE, createBlocker, recordBlocker, recordDecision, recordDiagnostic, retireDiagnostic } from "./diagnostics.js?v=fresh-20260801-2349-e938384";
import { FIRST_REACH_SETTLEMENTS, settlementInstitutionRecords } from "../content/economy/firstReachSettlements.js?v=fresh-20260801-2349-e938384";
import { FIRST_REACH_CARRIERS, carrierInstitutionRecords } from "../content/transportation/firstReachCarriers.js";
import { rankCarrierBids } from "./carrierSelection.js";
import { getRelationshipProjection } from "./relationshipProjections.js?v=fresh-20260801-2349-e938384";

// Until a carrier has actually paid for a repair, assume this much for upkeep.
const FREIGHT_REFERENCE_SERVICE_COST = 180;
const FREIGHT_REPRICE_INTERVAL_MS = 45 * 1000;
const FREIGHT_REPRICE_MAX_MULTIPLE = 2.5;
const CARRIER_DEFAULT_TRAITS = Object.freeze({ caution: 0.5, growthBias: 0.3 });

// Rolling carrier fleet policy, the same shape as Cinder's hiring: a carrier
// buys a ship when its own are plainly all committed, and lays one up when it
// plainly is not needed. Both are SUSTAINED conditions, not single ticks.
const HAULER_HIRE_AFTER_BUSY_SECONDS = 60;
const HAULER_RELEASE_AFTER_IDLE_SECONDS = 120;
const HAULER_COST = 6000;
const MIN_HAULERS = 1;
const MAX_HAULERS = 6;

const SITE_NAMES = Object.freeze({
  "yard-exchange": "Yard Exchange",
  "scrap-porch": "Scrap Porch",
  "the-ledge": "The Ledge",
  "blue-lantern": "Blue Lantern",
});

// The four authored freight routes that used to live here are gone.
//
// They ran whether or not anyone wanted the cargo: no buyer, no agreed sale, no
// downstream use. Every freight run is now generated by hubProcurement from a
// real purchase order — a buyer short of a family it may not mine, a supplier
// that agreed to sell, and goods that actually exist — so the offer board is
// derived rather than authored. See getProcurementFreightOffers.
//
// Kept as an empty export only so a save written before this still loads.
export const STANDING_FREIGHT_TEMPLATES = Object.freeze([]);

export function createInitialLogisticsState(now = Date.now()) {
  // Hubs open holding a working stock of the family they MINE, and nothing of
  // the families they must import. A settlement that has been feeding a
  // population does not start with an empty warehouse, and starting every hub
  // at zero made all three post critical-urgency mining orders at once and
  // outbid Sal's repair work. Import families stay at zero on purpose: that
  // shortfall is the interdependence, and it is what procurement has to solve.
  const settlementRecords = Object.fromEntries(settlementInstitutionRecords().map((record) => [
    record.id,
    JSON.parse(JSON.stringify(record)),
  ]));
  const carrierRecords = Object.fromEntries(carrierInstitutionRecords().map((record) => [record.id, record]));
  const haulers = Object.fromEntries(FIRST_REACH_CARRIERS.map((seed) => [seed.ship.physicalId, {
    shipInstitutionId: seed.ship.id,
    carrierInstitutionId: seed.institution.id,
    currentSiteId: seed.ship.homeSiteId,
    activeShipmentId: null,
    activeMovementId: null,
    maintenanceRequested: false,
    lastDecisionKey: null,
    status: "seeking-work",
  }]));
  return {
    version: 1,
    institutions: {
      ...settlementRecords,
      ...carrierRecords,
      // The people who actually run the three settlements. Their traits are the
      // ONLY thing that makes the hubs price differently from one another —
      // there is no per-hub code anywhere.
      //
      // Read them through the two factors that consume them: `caution` widens
      // the buffer a buyer wants, so it is willingness to PAY UP when short;
      // `growthBias` sets a seller's margin, so it is how hard they price what
      // they dig. Bex runs a supplied depot and does neither. Ivry runs the
      // furthest outpost, closest to going without, so she pays rather than run
      // dry and charges hard for the silicate only she has.
      // Dara runs thin and hungry; Mara is the careful one. `evaluateCarrierAsk`
      // has always read the controller's traits — until now neither person had
      // any, so both carriers quoted identically off a module constant.
    },
    haulers,
    shipments: {}, movements: {}, containers: {}, responses: {}, history: [{ id: "log-history-1", type: "logistics.instantiated", at: now }],
    counters: { shipment: 0, movement: 0, container: 0, response: 0, transaction: 0 }, lastLedgerEventId: 0,
  };
}

export function ensureLogisticsState(state, now = Date.now()) {
  state.logistics ??= createInitialLogisticsState(now);
  state.logistics.institutions ??= {};
  FIRST_REACH_SETTLEMENTS.forEach((seed) => {
    state.logistics.institutions[seed.institution.id] ??= JSON.parse(JSON.stringify(seed.institution));
  });
  FIRST_REACH_CARRIERS.forEach((seed) => {
    const institutionId = seed.institution.id;
    const institution = state.logistics.institutions[institutionId] ??= structuredClone(seed.institution);
    institution.policies ??= {};
    institution.policies.transportation ??= structuredClone(seed.policy);
    institution.repairOptions ??= structuredClone(seed.repairOptions);
    institution.name ??= seed.institution.name;
    institution.referenceId ??= seed.institution.referenceId;
    institution.accounts ??= structuredClone(seed.institution.accounts);
    institution.accounts.operating.id ??= seed.institution.accounts.operating.id;
    institution.accounts.operating.transactions ??= [];
    institution.policies.transportation.minimumOperatingCash ??= seed.policy.minimumOperatingCash;
    state.logistics.institutions[seed.controller.id] ??= structuredClone(seed.controller);
    state.logistics.institutions[seed.ship.id] ??= structuredClone(seed.ship);
    state.logistics.haulers ??= {};
    state.logistics.haulers[seed.ship.physicalId] ??= {
      shipInstitutionId: seed.ship.id, carrierInstitutionId: institutionId,
      currentSiteId: seed.ship.homeSiteId, activeShipmentId: null, activeMovementId: null,
      maintenanceRequested: false, lastDecisionKey: null, status: "seeking-work",
    };
  });

  // Hub controllers, for saves written before settlements had anyone running
  // them. Without these the three hubs fall back to one shared trait constant
  // and price identically, which is the thing this replaces.
  const hubControllers = Object.fromEntries(FIRST_REACH_SETTLEMENTS.map((seed) => [seed.institution.id, {
    ...seed.controller,
    siteId: seed.institution.siteId,
    hubName: seed.institution.name,
  }]));
  // Saves written when each settlement had its own decorative archetype id.
  // One `settlement` archetype now owns what all three actually share; what
  // makes them differ is their quartermaster, their rights and their shelf.
  const RETIRED_HUB_ARCHETYPES = ["trade-hub", "resource-outpost", "frontier-outpost"];
  Object.entries(hubControllers).forEach(([hubId, controller]) => {
    const hub = state.logistics.institutions[hubId];
    if (!hub) return;
    if (!hub.archetypeId || RETIRED_HUB_ARCHETYPES.includes(hub.archetypeId)) hub.archetypeId = "settlement";
    hub.siteId ??= controller.siteId;
    hub.name ??= controller.hubName;
    hub.controllerInstitutionId ??= controller.id;
    state.logistics.institutions[controller.id] ??= {
      id: controller.id, name: controller.name, archetypeId: "person",
      controls: [hubId], traits: controller.traits,
    };
  });
  state.logistics.movements ??= {};
  state.logistics.counters.movement ??= 0;
  state.logistics.counters.transaction ??= 0;
  Object.values(state.logistics.haulers ?? {}).forEach((hauler) => { hauler.activeMovementId ??= null; hauler.maintenanceRequested ??= false; hauler.lastDecisionKey ??= null; });
  return state.logistics;
}

export function createLogisticsManager({ state, ships = [], destinations = [], now = () => Date.now(), onProcurementDelivered = null, onProcurementShipped = null, commissionHauler = null, decommissionHauler = null }) {
  const logistics = ensureLogisticsState(state, now());
  const shipById = new Map(ships.map((ship) => [ship.id, ship]));
  const destinationRecords = destinations.length > 0
    ? destinations
    : Array.from(new Set(FIRST_REACH_TRANSPORT_CONNECTIONS.flatMap((connection) => [connection.fromId, connection.toId]))).map((id) => ({ id }));
  const transportationNetwork = createTransportationNetwork({ destinations: destinationRecords, connections: FIRST_REACH_TRANSPORT_CONNECTIONS });
  for (const [shipId, hauler] of Object.entries(logistics.haulers)) {
    const ship = shipById.get(shipId);
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    if (ship && shipInstitution) { ship.wear = shipInstitution.wear ?? 0; ship.wearIssueCount = shipInstitution.issueCount ?? 0; }
  }

  function update() {
    consumeEvents();
    repriceUnclaimedFreight();
    assessCarrierFleet();
    const freightWinners = selectFreightWinners();
    Object.entries(logistics.haulers).forEach(([shipId, hauler]) => {
      const ship = shipById.get(shipId);
      if (!ship) return;
      const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
      shipInstitution.wear = Math.max(shipInstitution.wear ?? 0, ship.wear ?? 0);
      if (hauler.activeShipmentId && ship.operationalStatus === "seeking-work") {
        const shipment = logistics.shipments[hauler.activeShipmentId];
        if (shipment?.status === "loaded") ship.assignShipment({ shipmentId: shipment.id, destinationSiteId: shipment.destinationSiteId });
      }
      if (!hauler.activeShipmentId && !hauler.activeMovementId && hauler.status === "seeking-work" && ship.operationalStatus !== "maintenance") {
        if (!assignNpcShipment(shipId, freightWinners)) assignMaintenanceAction(shipId);
      }
    });
  }

  function consumeEvents() {
    for (const event of state.ledger.getEventsAfterId(logistics.lastLedgerEventId, { includeHidden: true })) {
      logistics.lastLedgerEventId = Math.max(logistics.lastLedgerEventId, event.id);
      if (event.type === "npc.routeCompleted" && event.payload.shipmentId) {
        if (logistics.shipments[event.payload.shipmentId]) completeNpcShipment(event.payload.npcId, event.payload.shipmentId, event.payload.siteId);
        else if (logistics.movements[event.payload.shipmentId]) completeMaintenanceMovement(event.payload.npcId, event.payload.shipmentId, event.payload.siteId);
      }
      if (event.type === "npc.wearIssue") recordWearIssue(event.payload);
      if (event.type === "sprc.repairCompleted") {
        settleRepairInvoice(event.payload.haulerId, event.payload.serviceRevenue ?? 180, event.payload.repairOrderId);
        restoreAfterMaintenance(event.payload.haulerId);
      }
    }
  }

  // ── Supplier-side freight pricing ────────────────────────────────────────
  // The rate actually on offer for a template: the authored base until an
  // issuer raises it to attract a carrier.
  function getFreightRate(template) {
    logistics.postedFreightRates ??= {};
    return logistics.postedFreightRates[template.id] ?? template.payment;
  }

  // What this run costs the carrier, and therefore what it must be paid.
  // Maintenance is valued at what repairs CURRENTLY cost this carrier, so a
  // repair-price rise flows straight into freight asks.
  function isDueForMaintenance(carrier, shipInstitution) {
    const policy = carrier.policies?.transportation ?? {};
    const threshold = (policy.maximumWear ?? Infinity) - (policy.minimumReturnMargin ?? 0);
    return (shipInstitution?.wear ?? 0) >= threshold;
  }

  function repositionDistance(fromSiteId, toSiteId) {
    if (!fromSiteId || fromSiteId === toSiteId) return 0;
    const route = findTransportationRoute(transportationNetwork, fromSiteId, toSiteId);
    return route?.distance ?? 0;
  }

  function canReposition(fromSiteId, toSiteId) {
    return repositionDistance(fromSiteId, toSiteId) > 0;
  }

  function evaluateCarrierAsk({ template, plan, carrier, currentWear = 0, offeredPrice, repositionFrom = null }) {
    const distance = (plan?.route?.distance ?? 0) + repositionDistance(repositionFrom, template.originSiteId);
    const policy = carrier.policies?.transportation ?? {};
    const serviceCost = getServiceCost(state, carrier.id, "maintenance", FREIGHT_REFERENCE_SERVICE_COST);
    const maxWear = policy.maximumWear ?? 6;
    // Charge only the wear THIS run adds (plan.projectedWear is cumulative and
    // includes the ship's existing wear — billing that to one trip would make
    // every worn carrier refuse all work).
    const incrementalWear = Math.max(0, (plan?.projectedWear ?? currentWear) - currentWear);
    return evaluateSupplierAsk({
      workId: template.id,
      costComponents: {
        travel: distance * (policy.operatingCostPerDistance ?? 0.01),
        // Amortize: this run consumes incrementalWear/maxWear of a service cycle.
        maintenance: maxWear > 0 ? (incrementalWear / maxWear) * serviceCost : 0,
        time: 0,
      },
      offeredPrice,
      traits: getActorTraits(state, carrier.id, CARRIER_DEFAULT_TRAITS),
      policy,
      relationship: getRelationshipProjection(state, { fromId: carrier.id, toId: template.issuerInstitutionId }),
    });
  }

  function recordFreightAsk(template, ask) {
    logistics.freightAsks ??= {};
    logistics.freightAsks[template.id] = {
      templateId: template.id,
      ask: ask.recommendedPrice,
      floor: ask.minAcceptablePrice,
      costToServe: Math.round(ask.metrics.costToServe),
      acceptable: ask.acceptable,
      reasons: ask.reasons,
      at: now(),
    };
  }

  // A hub whose freight nobody will carry raises what it pays — bounded,
  // throttled, and logged, mirroring how Sal reprices unfilled purchase orders.
  function repriceUnclaimedFreight() {
    logistics.postedFreightRates ??= {};
    getProcurementFreightOffers(state).forEach((template) => {
      const ask = logistics.freightAsks?.[template.id];
      if (!ask || ask.acceptable) return;
      if (countActiveForTemplate(template.id) > 0) return;
      const lastRepricedAt = logistics.freightRepricedAt?.[template.id] ?? 0;
      if (now() - lastRepricedAt < FREIGHT_REPRICE_INTERVAL_MS) return;

      const current = getFreightRate(template);
      const ceiling = Math.round(template.payment * FREIGHT_REPRICE_MAX_MULTIPLE);
      const next = Math.min(ask.ask, ceiling);
      logistics.freightRepricedAt ??= {};
      logistics.freightRepricedAt[template.id] = now();
      if (next <= current) return;

      const issuer = logistics.institutions[template.issuerInstitutionId];
      const funding = evaluateAffordability({ account: issuer.accounts.operating, policy: { protectedCash: 0 }, cost: next });
      if (!funding.affordable) {
        appendHistory("freight.repriceDeferred", { templateId: template.id, wanted: next, reason: "issuer-cannot-fund" });
        return;
      }
      logistics.postedFreightRates[template.id] = next;
      appendHistory("freight.repriced", { templateId: template.id, previousPayment: current, payment: next, carrierCost: ask.costToServe });
      state.ledger.recordEvent("institution.freightRepriced", {
        institutionId: template.issuerInstitutionId, templateId: template.id, previousPayment: current, payment: next,
        carrierCost: ask.costToServe,
        reasons: [`No carrier would run ${template.originName}→${template.destinationName} at ${current} cr.`, ...ask.reasons],
      }, { visible: true, message: `${siteName(template.destinationSiteId)} raises ${template.commodityName} freight to ${next} cr — carriers cannot cover ${ask.costToServe} cr of cost at ${current}.` });
    });
  }

  // Diagnostics for an idle carrier. The chain matters most here: "no cargo"
  // is usually caused by a source hub being empty, which is caused by whoever
  // was supposed to supply it.
  function publishCarrierDiagnosticBlocker(shipId, hauler, candidates, declined) {
    const context = getCarrierContext(shipId);
    const site = hauler.currentSiteId;
    const localTemplates = getProcurementFreightOffers(state).filter((template) => template.originSiteId === site);
    const outOfStock = localTemplates.filter((template) => (logistics.institutions[template.sourceInstitutionId]?.inventories?.[template.commodity] ?? 0) < template.amount);

    const causes = [];
    // Nothing on the board is now usually caused by a supplier that has agreed
    // to sell and not yet dug the material up. Name it, so the chain continues
    // into that hub's own record rather than stopping at "no cargo".
    if (localTemplates.length === 0) {
      listOrders(state, { status: PROCUREMENT_STATUS.ACCEPTED }).forEach((order) => {
        const held = logistics.institutions[order.supplierInstitutionId]?.inventories?.[order.resourceId] ?? 0;
        causes.push({
          kind: BLOCKER_KIND.SOURCE_OUT_OF_STOCK,
          summary: `${order.supplierInstitutionId} owes ${order.units} ${order.resourceId.replaceAll("-", " ")} on ${order.id} and holds ${held}`,
          subjectId: order.supplierInstitutionId,
          objectId: order.id,
          causedBy: [{ actorId: order.supplierInstitutionId }],
        });
      });
    }
    outOfStock.forEach((template) => {
      // Who is supposed to be filling that shelf? Point at the supplier so the
      // chain continues into their own reasoning.
      const supplierId = state.miningOperation?.institution?.id ?? null;
      causes.push({
        kind: BLOCKER_KIND.SOURCE_OUT_OF_STOCK,
        summary: `${siteName(template.originSiteId)} has no ${template.commodityName} to ship (${template.sourceInstitutionId} holds ${logistics.institutions[template.sourceInstitutionId]?.inventories?.[template.commodity] ?? 0})`,
        subjectId: template.sourceInstitutionId,
        objectId: template.id,
        waitingFor: `${template.commodityName} to arrive in local supply`,
        wakeOn: ["inventory-delivered"],
        causedBy: supplierId ? [{ actorId: supplierId, note: `no ${template.commodityName} has been delivered` }] : [],
        at: now(),
      });
    });
    candidates.filter((candidate) => !candidate.plan.eligible && candidate.plan.reason === "below-carrier-cost").forEach((candidate) => {
      causes.push({
        kind: BLOCKER_KIND.BELOW_COST,
        summary: `${candidate.template.id} pays ${candidate.rate} but costs ${Math.round(candidate.ask?.metrics?.costToServe ?? 0)} to run`,
        subjectId: shipId,
        objectId: candidate.template.id,
        waitingFor: `a rate of at least ${candidate.ask?.minAcceptablePrice ?? "cost"}`,
        wakeOn: ["freight-repriced"],
        at: now(),
      });
    });
    candidates.filter((candidate) => !candidate.plan.eligible && candidate.plan.reason === "payer-cannot-fund").forEach((candidate) => {
      causes.push({
        kind: BLOCKER_KIND.PAYER_CANNOT_FUND,
        summary: `${candidate.template.issuerInstitutionId} cannot fund ${candidate.rate} cr for ${candidate.template.id}`,
        subjectId: candidate.template.issuerInstitutionId,
        objectId: candidate.template.id,
        waitingFor: "the issuer to hold enough cash",
        wakeOn: ["issuer-income"],
        at: now(),
      });
    });

    recordDiagnostic(state, shipId, {
      actorName: context.carrierName ?? shipId,
      actorKind: "ship",
      controllerId: hauler.carrierInstitutionId,
      locationSiteId: site,
      intention: null,
    }, now());
    recordBlocker(state, shipId, createBlocker({
      kind: BLOCKER_KIND.NO_ELIGIBLE_CARGO,
      summary: `${context.pilotName ?? shipId} is docked at ${siteName(site)} with no eligible freight${declined ? ` (${formatReason(declined.plan.reason)})` : ""}`,
      subjectId: shipId,
      objectId: site,
      waitingFor: outOfStock.length ? "cargo to appear in local supply" : "an offer that clears its cost",
      wakeOn: ["inventory-delivered", "freight-repriced", "offer-posted"],
      causedBy: causes,
      detail: { evaluated: candidates.length, declinedReason: declined?.plan.reason ?? "none-offered" },
      at: now(),
    }), { state: DIAGNOSTIC_STATE.WAITING, at: now() });
  }

  function buildCarrierCandidates(shipId, { recordAsks = false } = {}) {
    const hauler = logistics.haulers[shipId];
    const ship = shipById.get(shipId);
    if (!ship || ship.dockedSiteId !== hauler.currentSiteId || hauler.activeShipmentId || hauler.activeMovementId || hauler.status !== "seeking-work" || ship.operationalStatus === "maintenance") return [];
    const carrier = logistics.institutions[hauler.carrierInstitutionId];
    const account = carrier.accounts.operating;
    if (account.balance < 0) return [];
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    // Every run on the board is backed by a purchase order whose goods exist.
    const offered = getProcurementFreightOffers(state);
    const hasLoadableLocalWork = offered.some((entry) => entry.originSiteId === hauler.currentSiteId
      && countActiveForTemplate(entry.id) < 1
      && availableToLoad(entry) >= entry.amount);
    const candidates = offered
      .filter((entry) => countActiveForTemplate(entry.id) < 1)
      .filter((entry) => availableToLoad(entry) >= entry.amount)
      // A hauler may take a contract from either end of the relationship: if it
      // is not already at the pickup, it flies there empty first and the cost of
      // that leg is priced into what it will accept.
      .map((template) => ({ template, repositionFrom: template.originSiteId === hauler.currentSiteId ? null : hauler.currentSiteId }))
      // Take what is in front of you. A hauler only flies to the far end of a
      // relationship when there is nothing loadable where it already is, and
      // never when it is due for service — reaching further is for healthy
      // hulls. This is what lets either end of a trade lane be served without
      // changing how a carrier behaves when work is already local.
      .filter(({ template, repositionFrom }) => {
        if (!repositionFrom) return true;
        if (hasLoadableLocalWork || isDueForMaintenance(carrier, shipInstitution)) return false;
        return canReposition(hauler.currentSiteId, template.originSiteId);
      })
      .map(({ template, repositionFrom }) => {
        const rate = getFreightRate(template);
        const plan = evaluateTransportPlan({ network: transportationNetwork, originId: template.originSiteId, destinationId: template.destinationSiteId, payment: rate, currentWear: shipInstitution.wear ?? 0, policy: carrier.policies?.transportation, repairOptions: carrier.repairOptions });
        const issuer = logistics.institutions[template.issuerInstitutionId];
        const funding = evaluateAffordability({ account: issuer.accounts.operating, policy: { protectedCash: 0 }, cost: rate });
        // Supplier-side pricing: the carrier totals what the run costs it —
        // including the maintenance it will owe at CURRENT repair prices — and
        // refuses work that does not clear that cost.
        const ask = evaluateCarrierAsk({ template, plan, carrier, currentWear: shipInstitution.wear ?? 0, offeredPrice: rate, repositionFrom });
        if (recordAsks) recordFreightAsk(template, ask);
        let resolved = plan;
        if (plan.eligible && !funding.affordable) resolved = { ...plan, eligible: false, reason: "payer-cannot-fund", funding };
        else if (plan.eligible && !ask.acceptable) resolved = { ...plan, eligible: false, reason: "below-carrier-cost", ask };
        return { template, plan: resolved, ask, rate, repositionFrom };
      });
    return candidates;
  }

  function selectFreightWinners() {
    const bidsByTemplate = new Map();
    Object.keys(logistics.haulers).sort().forEach((shipId) => {
      const hauler = logistics.haulers[shipId];
      const carrier = logistics.institutions[hauler.carrierInstitutionId];
      const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
      buildCarrierCandidates(shipId).forEach((candidate) => {
        const bid = {
          offerId: candidate.template.id,
          carrierId: carrier.id,
          shipId,
          eligible: candidate.plan.eligible,
          committed: Boolean(hauler.activeShipmentId || hauler.activeMovementId),
          offeredPrice: candidate.rate,
          askingPrice: candidate.ask.recommendedPrice,
          costToServe: candidate.ask.metrics.costToServe,
          currentWear: shipInstitution.wear ?? 0,
          repositionDistance: repositionDistance(candidate.repositionFrom, candidate.template.originSiteId),
          relationship: getRelationshipProjection(state, { fromId: candidate.template.issuerInstitutionId, toId: carrier.id }),
        };
        const list = bidsByTemplate.get(candidate.template.id) ?? [];
        list.push(bid);
        bidsByTemplate.set(candidate.template.id, list);
      });
    });
    const winners = new Map();
    logistics.carrierBidDiagnostics ??= {};
    bidsByTemplate.forEach((bids, templateId) => {
      const ranked = rankCarrierBids(bids);
      const winner = ranked.find((bid) => Number.isFinite(bid.selectionScore)) ?? null;
      logistics.carrierBidDiagnostics[templateId] = { templateId, bids: ranked.map((bid) => ({ ...bid, relationship: bid.relationship ? { id: bid.relationship.id } : null })), winnerShipId: winner?.shipId ?? null, at: now() };
      if (winner) winners.set(templateId, winner.shipId);
    });
    return winners;
  }

  function assignNpcShipment(shipId, freightWinners = null) {
    const hauler = logistics.haulers[shipId];
    const ship = shipById.get(shipId);
    if (!ship) return null;
    if (ship.dockedSiteId !== hauler.currentSiteId) {
      publishDecisionOnce(shipId, `waiting-dock:${hauler.currentSiteId}:${ship.dockedSiteId ?? "none"}`, `${getCarrierContext(shipId).pilotName} is holding outside ${siteName(hauler.currentSiteId)}; a freight contract cannot be accepted until the hauler docks.`, { reason: "not-docked", currentSiteId: hauler.currentSiteId, dockedSiteId: ship.dockedSiteId ?? null });
      return null;
    }
    const carrier = logistics.institutions[hauler.carrierInstitutionId];
    const account = carrier.accounts.operating;
    if (account.balance < 0) {
      publishDecisionOnce(shipId, `insolvent:${account.balance}`, `${getCarrierContext(shipId).carrierName} cannot accept freight: account ${account.id} is overdrawn at ${account.balance} cr.`, { reason: "insolvent", balance: account.balance });
      return null;
    }
    const candidates = buildCarrierCandidates(shipId, { recordAsks: true });
    candidates.filter((candidate) => !candidate.plan.eligible).forEach((candidate) => appendHistory("freight.declined", { shipId, templateId: candidate.template.id, reason: candidate.plan.reason }));
    const selected = candidates.filter((candidate) => candidate.plan.eligible)
      .filter((candidate) => !freightWinners || freightWinners.get(candidate.template.id) === shipId)
      .sort((a, b) => b.plan.score - a.plan.score || a.template.id.localeCompare(b.template.id))[0];
    if (!selected) {
      const declined = candidates.find((candidate) => !candidate.plan.eligible);
      publishCarrierDiagnosticBlocker(shipId, hauler, candidates, declined);
      publishDecisionOnce(shipId, `no-work:${hauler.currentSiteId}:${declined?.plan.reason ?? "none-offered"}`, `${getCarrierContext(shipId).pilotName} is docked at ${siteName(hauler.currentSiteId)} but found no eligible freight${declined ? ` (${formatReason(declined.plan.reason)})` : ""}; checking service needs.`, { reason: declined?.plan.reason ?? "no-offer", currentSiteId: hauler.currentSiteId });
      if (candidates.some((candidate) => candidate.plan.reason === "maintenance-policy")) return assignMaintenanceAction(shipId, { force: true });
      return null;
    }
    const { template, plan } = selected;
    const responseId = `LOG-RSP-${++logistics.counters.response}`;
    const policy = resolveInstitutionPolicy({ institutionPolicy: { protectedCash: 100 } });
    const capability = { id: "transport-freight", canAddress: () => true, propose: () => [{ capabilityId: "transport-freight", action: "accept-shipment", purpose: "earn-operating-revenue", estimatedCost: 0, rationale: `Carry available freight from ${template.originName} to ${template.destinationName}.` }] };
    const proposal = generateCapabilityResponses({ institution: carrier, needs: [{ id: `work:${shipId}`, status: "open", urgency: "routine", purpose: "earn-operating-revenue" }], capabilities: [capability], policy })[0];
    logistics.responses[responseId] = { ...createResponseRecord({ id: responseId, needIds: [`work:${shipId}`], capabilityId: proposal.capabilityId, action: proposal.action, rationale: proposal.rationale, priorityScore: proposal.priorityScore, selectedAt: now() }), status: "active" };
    const shipment = createShipment({ template, assigneeType: "npc", assigneeId: shipId, responseId, plan, repositionFrom: selected.repositionFrom ?? null });
    if (!shipment) {
      logistics.responses[responseId].status = "blocked";
      logistics.responses[responseId].lastOutcome = { type: "execution-route-rejected", at: now() };
      appendHistory("freight.declined", { shipId, templateId: template.id, reason: "execution-route-rejected" });
    } else {
      hauler.lastDecisionKey = null;
      // Diagnostics: committed to a run, with the cost/ask that justified it and
      // the alternatives that lost.
      recordDiagnostic(state, shipId, {
        actorName: getCarrierContext(shipId).carrierName ?? shipId,
        actorKind: "ship",
        controllerId: hauler.carrierInstitutionId,
        state: DIAGNOSTIC_STATE.COMMITTED,
        summary: `Hauling ${template.commodityName} ${template.originName} → ${template.destinationName} for ${shipment.payment} cr`,
        locationSiteId: hauler.currentSiteId,
        // The shared record, not a second shape describing the same thing.
        intention: adaptShipment(shipment),
        blocker: null,
        waitingFor: null,
        wakeOn: ["shipment-delivered", "breakdown"],
        nextReconsiderAt: null,
        refs: { contractIds: [shipment.contractId].filter(Boolean), targetIds: [template.destinationSiteId], dependencyIds: [shipment.containerId] },
      }, now());
      recordDecision(state, shipId, {
        chosen: { id: template.id, label: `${template.commodityName} → ${template.destinationName}`, score: shipment.payment },
        alternatives: candidates
          .filter((candidate) => candidate.template.id !== template.id)
          .map((candidate) => ({
            id: candidate.template.id,
            label: `${candidate.template.commodityName} → ${candidate.template.destinationName}`,
            score: candidate.rate,
            rejectedBecause: candidate.plan.eligible ? "lower score" : formatReason(candidate.plan.reason),
          })),
        reasons: selected.ask?.reasons ?? [],
        at: now(),
      });
      publishCarrierEvent("carrier.contractAccepted", shipId, { shipmentId: shipment.id, templateId: template.id, payment: shipment.payment, originSiteId: template.originSiteId, destinationSiteId: template.destinationSiteId, projectedWear: plan.projectedWear, carrierCost: Math.round(selected.ask?.metrics?.costToServe ?? 0), carrierAsk: selected.ask?.recommendedPrice ?? null }, `${getCarrierContext(shipId).pilotName} accepted ${shipment.payment} cr freight from ${template.originName} to ${template.destinationName}; account balance is ${account.balance} cr.`);
    }
    return shipment;
  }

  // A run carrying goods that already belong to the destination. No sale, no
  // payment to the seller: the only money here is the carrier's fee, which the
  // owner of the cargo pays.
  function createPrepaidShipment({ template, assigneeType, assigneeId, responseId, contractId, plan, repositionFrom, routeSites, rate, held }) {
    const issuer = logistics.institutions[template.issuerInstitutionId];
    issuer.accounts.operating.committed += rate;
    const id = `SHIP-${String(++logistics.counters.shipment).padStart(4, "0")}`;
    const containerId = `CONT-${String(++logistics.counters.container).padStart(4, "0")}`;
    logistics.containers[containerId] = {
      id: containerId, shipmentId: id, commodity: template.commodity, quantity: template.amount,
      // Custody sits with the carrier; ownership never leaves the buyer.
      ownerInstitutionId: template.destinationInstitutionId,
      custodianInstitutionId: template.sourceInstitutionId,
      manifestId: held.manifestId ?? null,
      custody: [{ institutionId: template.sourceInstitutionId, action: "released-to-carrier", siteId: template.originSiteId, at: now() }],
    };
    const shipment = logistics.shipments[id] = {
      id, templateId: template.id, contractId, responseId, assigneeType, assigneeId, containerId,
      originSiteId: template.originSiteId, destinationSiteId: template.destinationSiteId,
      sourceInstitutionId: template.sourceInstitutionId, destinationInstitutionId: template.destinationInstitutionId,
      issuerInstitutionId: template.issuerInstitutionId, commodity: template.commodity, quantity: template.amount,
      payment: rate, committedPayment: rate, basePayment: template.payment,
      goodsPayment: 0, prepaid: true, manifestId: held.manifestId ?? null,
      procurementOrderId: template.procurementOrderId ?? null, repositionedFrom: repositionFrom ?? null,
      status: "assigned", createdAt: now(), loadedAt: null,
    };
    appendHistory("shipment.assigned", { shipmentId: id, containerId, assigneeId, commodity: template.commodity, prepaid: true });
    state.ledger.recordEvent("logistics.prepaidCargoCollected", {
      shipmentId: id, manifestId: held.manifestId ?? null, ownerId: template.destinationInstitutionId,
      heldAtId: template.sourceInstitutionId, commodity: template.commodity, quantity: template.amount, freight: rate,
    }, { visible: true, message: `A carrier collected ${template.amount} ${template.commodityName} held at ${template.originName} under ${held.manifestId ?? "manifest"} and owned by ${template.destinationName}.` });

    const assignedShip = assigneeType === "npc" ? shipById.get(assigneeId) : null;
    if (assigneeType === "npc" && assignedShip) {
      loadShipment(shipment);
      if (shipment.procurementOrderId) onProcurementShipped?.(shipment.procurementOrderId, shipment.id);
      const hauler = logistics.haulers[assigneeId];
      hauler.activeShipmentId = id; hauler.status = "transporting";
      assignedShip.assignShipment({ shipmentId: id, destinationSiteId: template.destinationSiteId, route: routeSites });
    }
    return shipment;
  }

  function createShipment({ template, assigneeType, assigneeId, responseId = null, contractId = null, plan = null, repositionFrom = null }) {
    const haulRoute = plan?.route ? buildPhysicalTransportationRoute(transportationNetwork, plan.route) : [];
    // A hauler taking work from the far end flies to the pickup empty first, so
    // its route is the deadhead leg followed by the loaded leg.
    const approach = repositionFrom ? findTransportationRoute(transportationNetwork, repositionFrom, template.originSiteId) : null;
    const approachSites = approach ? buildPhysicalTransportationRoute(transportationNetwork, approach) : [];
    const routeSites = approachSites.length > 1 ? [...approachSites.slice(0, -1), ...haulRoute] : haulRoute;
    const assignedShip = assigneeType === "npc" ? shipById.get(assigneeId) : null;
    if (assigneeType === "npc" && (!assignedShip || (assignedShip.canAcceptRoute ? !assignedShip.canAcceptRoute(routeSites) : routeSites.length < 2))) return null;
    const issuer = logistics.institutions[template.issuerInstitutionId];
    // The posted rate, which may have been raised above the authored base to
    // attract a carrier, is the single price used for funding, commitment, and
    // settlement.
    const rate = getFreightRate(template);
    const affordability = evaluateAffordability({ account: issuer.accounts.operating, policy: { protectedCash: 0 }, cost: rate });
    if (!affordability.affordable) return null;
    const source = logistics.institutions[template.sourceInstitutionId];
    if (!template.prepaid && (source.inventories[template.commodity] ?? 0) < template.amount) return null;

    // Prepaid freight is moving property the buyer already owns: title changed
    // hands when the sale completed, so there is nothing to buy here and the
    // goods come out of the awaiting-pickup manifest rather than the seller's
    // own shelf.
    if (template.prepaid) {
      const held = source.awaitingPickup?.[template.procurementOrderId];
      if (!held || held.units < template.amount) return null;
      delete source.awaitingPickup[template.procurementOrderId];
      return createPrepaidShipment({ template, assigneeType, assigneeId, responseId, contractId, plan, repositionFrom, routeSites, rate, held });
    }

    // Buy the goods from the seller. The buyer must be able to cover the sale
    // AND the freight, or no shipment is created — an unaffordable trade is
    // withheld rather than half-executed.
    const goods = quoteGoods(template.sourceInstitutionId, template.commodity, template.amount);
    const buyerId = template.destinationInstitutionId;
    const buyerAccount = logistics.institutions[buyerId]?.accounts?.operating ?? {};
    if ((buyerAccount.balance ?? 0) < goods.price + rate) {
      recordBlocker(state, buyerId, createBlocker({
        kind: BLOCKER_KIND.PAYER_CANNOT_AFFORD,
        summary: `${buyerId} cannot buy ${template.amount} ${template.commodityName}: ${goods.price} cr of goods plus ${rate} cr freight exceeds its balance`,
        subjectId: buyerId, objectId: template.id,
        waitingFor: "revenue, or a cheaper supplier",
        wakeOn: ["population.goodsPurchased", "order-repriced"],
        detail: { templateId: template.id, goodsPrice: goods.price, freight: rate, balance: Math.round(buyerAccount.balance ?? 0) },
        at: now(),
      }), { state: DIAGNOSTIC_STATE.WAITING, at: now() });
      return null;
    }

    source.inventories[template.commodity] -= template.amount;
    recordAccountTransaction(buyerId, -goods.price, "goods-purchase", template.id, `Bought ${template.amount} ${template.commodityName} from ${template.sourceInstitutionId}`);
    recordAccountTransaction(template.sourceInstitutionId, goods.price, "goods-sale", template.id, `Sold ${template.amount} ${template.commodityName} to ${buyerId}`);
    state.ledger.recordEvent("logistics.goodsSold", {
      sellerId: template.sourceInstitutionId, buyerId, commodity: template.commodity,
      quantity: template.amount, price: goods.price, unitCost: Math.round(goods.unitCost),
      freight: rate, reasons: goods.valuation.reasons,
    }, { visible: true, message: `${template.sourceInstitutionId} sold ${template.amount} ${template.commodityName} to ${buyerId} for ${goods.price} cr, with ${rate} cr freight on top.` });

    issuer.accounts.operating.committed += rate;
    const id = `SHIP-${String(++logistics.counters.shipment).padStart(4, "0")}`;
    const containerId = `CONT-${String(++logistics.counters.container).padStart(4, "0")}`;
    const container = logistics.containers[containerId] = { id: containerId, shipmentId: id, commodity: template.commodity, quantity: template.amount, ownerInstitutionId: template.sourceInstitutionId, custodianInstitutionId: template.sourceInstitutionId, custody: [{ institutionId: template.sourceInstitutionId, action: "created", siteId: template.originSiteId, at: now() }] };
    const shipment = logistics.shipments[id] = { id, templateId: template.id, contractId, responseId, assigneeType, assigneeId, containerId, originSiteId: template.originSiteId, destinationSiteId: template.destinationSiteId, sourceInstitutionId: template.sourceInstitutionId, destinationInstitutionId: template.destinationInstitutionId, issuerInstitutionId: template.issuerInstitutionId, commodity: template.commodity, quantity: template.amount, payment: rate, committedPayment: rate, basePayment: template.payment, goodsPayment: goods.price, goodsUnitCost: goods.unitCost, procurementOrderId: template.procurementOrderId ?? null, repositionedFrom: repositionFrom ?? null, status: "assigned", createdAt: now(), loadedAt: null };
    appendHistory("shipment.assigned", { shipmentId: id, containerId, assigneeId, commodity: template.commodity });
    if (assigneeType === "npc") {
      loadShipment(shipment);
      if (shipment.procurementOrderId) onProcurementShipped?.(shipment.procurementOrderId, shipment.id);
      const hauler = logistics.haulers[assigneeId];
      hauler.activeShipmentId = id; hauler.status = "transporting";
      assignedShip.assignShipment({ shipmentId: id, destinationSiteId: template.destinationSiteId, route: routeSites });
      publishCarrierEvent("carrier.freightLoaded", assigneeId, { shipmentId: id, commodity: template.commodity, quantity: template.amount, destinationSiteId: template.destinationSiteId }, `${getCarrierContext(assigneeId).shipName} loaded ${template.amount} ${template.commodityName} for ${template.destinationName}.`);
    }
    return shipment;
  }

  function assignMaintenanceAction(shipId, options = {}) {
    const hauler = logistics.haulers[shipId];
    const ship = shipById.get(shipId);
    const carrier = logistics.institutions[hauler.carrierInstitutionId];
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    const policy = carrier.policies?.transportation ?? {};
    const threshold = (policy.maximumWear ?? Infinity) - (policy.minimumReturnMargin ?? 0);
    if (!options.force && (shipInstitution.wear ?? 0) < threshold) return null;
    const repairRoutes = carrier.repairOptions
      .map((option) => ({ option, route: findTransportationRoute(transportationNetwork, hauler.currentSiteId, option.destinationId, policy.knownDestinationIds) }))
      .filter((entry) => entry.route)
      .sort((a, b) => (a.option.priority ?? 0) - (b.option.priority ?? 0) || a.route.distance - b.route.distance);
    const selected = repairRoutes[0];
    if (!selected) { appendHistory("maintenance.blocked", { shipId, reason: "no-reachable-maintenance" }); return null; }
    if (hauler.currentSiteId === selected.option.destinationId) return requestPreventiveMaintenance(shipId);
    const routeSites = selected.route.path.map((id) => transportationNetwork.destinations[id]);
    if (ship.canAcceptRoute ? !ship.canAcceptRoute(routeSites) : routeSites.length < 2) { appendHistory("maintenance.blocked", { shipId, reason: "execution-route-rejected" }); return null; }
    const id = `MOVE-${String(++logistics.counters.movement).padStart(4, "0")}`;
    logistics.movements[id] = { id, type: "service-return", shipId, originSiteId: hauler.currentSiteId, destinationSiteId: selected.option.destinationId, providerInstitutionId: selected.option.institutionId, status: "active", createdAt: now() };
    hauler.activeMovementId = id; hauler.status = "returning-maintenance";
    ship.assignShipment({ shipmentId: id, destinationSiteId: selected.option.destinationId, route: routeSites });
    appendHistory("maintenance.returnStarted", { movementId: id, shipId, destinationSiteId: selected.option.destinationId });
    publishCarrierEvent("carrier.maintenanceReturn", shipId, { movementId: id, destinationSiteId: selected.option.destinationId, wear: shipInstitution.wear ?? 0 }, `${getCarrierContext(shipId).pilotName} declined further freight and is returning ${getCarrierContext(shipId).shipName} to ${siteName(selected.option.destinationId)} for service.`);
    return logistics.movements[id];
  }

  function completeMaintenanceMovement(shipId, movementId, siteId) {
    const movement = logistics.movements[movementId];
    if (!movement || movement.status !== "active" || movement.destinationSiteId !== siteId) return false;
    movement.status = "completed"; movement.completedAt = now();
    const hauler = logistics.haulers[shipId];
    hauler.currentSiteId = siteId; hauler.activeMovementId = null;
    shipById.get(shipId)?.clearShipment();
    appendHistory("maintenance.returnCompleted", { movementId, shipId, siteId });
    publishCarrierEvent("carrier.arrivedForMaintenance", shipId, { movementId, siteId }, `${getCarrierContext(shipId).shipName} arrived at ${siteName(siteId)} and is requesting service.`);
    requestPreventiveMaintenance(shipId);
    return true;
  }

  function requestPreventiveMaintenance(shipId) {
    const hauler = logistics.haulers[shipId];
    if (hauler.maintenanceRequested) return null;
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    hauler.maintenanceRequested = true; hauler.status = "maintenance-required";
    const ship = shipById.get(shipId); if (ship) ship.operationalStatus = "maintenance";
    const maintenancePayload = { npcId: shipId, issueType: "preventive-service", wear: shipInstitution.wear ?? 0, issueCount: shipInstitution.issueCount ?? 0, causedByCarefulMode: false };
    state.ledger.recordEvent("logistics.maintenanceRequired", maintenancePayload, { visible: false });
    publishMaintenanceRequest(shipId, maintenancePayload);
    publishCarrierEvent("carrier.maintenanceRequested", shipId, maintenancePayload, `${getCarrierContext(shipId).pilotName} placed ${getCarrierContext(shipId).shipName} in Scrap Porch's service queue at wear ${(shipInstitution.wear ?? 0).toFixed(2)}.`);
    appendHistory("maintenance.requested", { shipId, issueType: "preventive-service" });
    return true;
  }

  function restoreAfterMaintenance(shipId) {
    const hauler = logistics.haulers[shipId];
    if (!hauler) return;
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    shipInstitution.wear = 0; shipInstitution.issueCount = 0;
    hauler.maintenanceRequested = false; hauler.status = "seeking-work";
    const ship = shipById.get(shipId);
    if (ship) { ship.wear = 0; ship.wearIssueCount = 0; ship.pendingWearIssue = null; ship.operationalStatus = "seeking-work"; }
    appendHistory("maintenance.restored", { shipId });
    publishCarrierEvent("carrier.maintenanceCompleted", shipId, { wear: 0 }, `${getCarrierContext(shipId).shipName} cleared maintenance and returned to freight service.`);
  }

  function completeNpcShipment(shipId, shipmentId, siteId) {
    const shipment = logistics.shipments[shipmentId];
    if (!shipment || shipment.status !== "loaded" || shipment.destinationSiteId !== siteId) return false;
    completeShipment(shipment);
    const hauler = logistics.haulers[shipId];
    hauler.currentSiteId = siteId; hauler.activeShipmentId = null; hauler.status = "seeking-work";
    shipById.get(shipId)?.clearShipment();
    return true;
  }

  function completeShipment(shipment) {
    const container = logistics.containers[shipment.containerId];
    transferCustody(container, shipment.destinationInstitutionId, "unloaded", shipment.destinationSiteId);
    container.ownerInstitutionId = shipment.destinationInstitutionId;
    logistics.institutions[shipment.destinationInstitutionId].inventories[shipment.commodity] = (logistics.institutions[shipment.destinationInstitutionId].inventories[shipment.commodity] ?? 0) + shipment.quantity;
    // Landed cost, not just the sale price: the buyer really paid for the
    // goods and the freight to get them here, and anything built from this
    // material should carry both.
    recordAcquisition(state, {
      institutionId: shipment.destinationInstitutionId, itemId: shipment.commodity,
      units: shipment.quantity, totalCost: (shipment.goodsPayment ?? 0) + (shipment.payment ?? 0),
      source: "freight-purchase", at: now(),
    });
    const issuer = logistics.institutions[shipment.issuerInstitutionId];
    recordAccountTransaction(shipment.issuerInstitutionId, -shipment.payment, "freight-payment", shipment.id, `Paid freight delivery ${shipment.id}`);
    issuer.accounts.operating.committed = Math.max(0, issuer.accounts.operating.committed - shipment.payment);
    shipment.committedPayment = 0; shipment.status = "delivered"; shipment.deliveredAt = now();
    if (shipment.assigneeType === "npc") {
      const carrierId = logistics.haulers[shipment.assigneeId].carrierInstitutionId;
      const transaction = recordAccountTransaction(carrierId, shipment.payment, "freight-income", shipment.id, `Completed freight delivery ${shipment.id}`);
      shipById.get(shipment.assigneeId)?.queueCargoTransfer?.({ commodity: shipment.commodity, direction: "to-hub" });
      publishCarrierEvent("carrier.contractFulfilled", shipment.assigneeId, { shipmentId: shipment.id, payment: shipment.payment, transactionId: transaction.id, balance: transaction.balance, destinationSiteId: shipment.destinationSiteId }, `${getCarrierContext(shipment.assigneeId).pilotName} delivered ${shipment.commodity} to ${siteName(shipment.destinationSiteId)}, earned ${shipment.payment} cr, and now has ${transaction.balance} cr.`);
    }
    // A procurement-backed run closes the order that caused it, which is what
    // reduces the buyer's real need rather than just moving material about.
    if (shipment.procurementOrderId) {
      onProcurementDelivered?.(shipment.procurementOrderId, {
        deliveredUnits: shipment.quantity,
        goodsPayment: shipment.goodsPayment ?? 0,
        freightPaid: shipment.payment ?? 0,
      });
    }
    appendHistory("shipment.delivered", { shipmentId: shipment.id, containerId: container.id, payment: shipment.payment });
  }

  function acceptPlayerContract(contract, playerInstitutionId) {
    const template = getProcurementFreightOffers(state).find((entry) => entry.id === contract.terms.standingFreightTemplateId);
    if (!template || countActiveForTemplate(template.id) >= 2) return null;
    return createShipment({ template, assigneeType: "player", assigneeId: playerInstitutionId, contractId: contract.id });
  }

  function loadPlayerContract(contractId) {
    const shipment = Object.values(logistics.shipments).find((entry) => entry.contractId === contractId && entry.status === "assigned");
    return shipment ? loadShipment(shipment) : false;
  }

  function deliverPlayerContract(contractId) {
    const shipment = Object.values(logistics.shipments).find((entry) => entry.contractId === contractId && entry.status === "loaded");
    if (!shipment) return false;
    completeShipment(shipment);
    return true;
  }

  function loadShipment(shipment) {
    if (shipment.status !== "assigned") return false;
    const custodianId = shipment.assigneeType === "npc" ? logistics.haulers[shipment.assigneeId].carrierInstitutionId : shipment.assigneeId;
    transferCustody(logistics.containers[shipment.containerId], custodianId, "loaded", shipment.originSiteId);
    if (shipment.assigneeType === "npc") shipById.get(shipment.assigneeId)?.queueCargoTransfer?.({ commodity: shipment.commodity, direction: "from-hub" });
    shipment.status = "loaded"; shipment.loadedAt = now();
    appendHistory("shipment.loaded", { shipmentId: shipment.id, containerId: shipment.containerId, assigneeId: shipment.assigneeId });
    return true;
  }

  function recordWearIssue(payload) {
    const hauler = logistics.haulers[payload.npcId];
    if (!hauler) return;
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    shipInstitution.wear = payload.wear; shipInstitution.issueCount = payload.issueCount;
    hauler.maintenanceRequested = true; hauler.status = "maintenance-required";
    shipById.get(payload.npcId).operationalStatus = "maintenance";
    appendHistory("ship.issue", payload);
    state.ledger.recordEvent("logistics.maintenanceRequired", payload, { visible: false });
    publishMaintenanceRequest(payload.npcId, payload);
    publishCarrierEvent("carrier.breakdown", payload.npcId, payload, `${getCarrierContext(payload.npcId).shipName} suffered a ${formatReason(payload.issueType ?? "wear issue")} at wear ${(payload.wear ?? 0).toFixed(2)}; ${getCarrierContext(payload.npcId).pilotName} is seeking repair.`);
  }

  function publishMaintenanceRequest(shipId, payload) {
    const hauler = logistics.haulers[shipId];
    const carrier = logistics.institutions[hauler.carrierInstitutionId];
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    const requiredCapabilities = payload.issueType === "hull-fatigue" ? ["structural-repair"] : payload.issueType === "control-fault" ? ["control-systems"] : ["mechanical-repair"];
    state.ledger.recordEvent("maintenance.requested", { subjectId: shipId, subjectName: shipInstitution.name, referenceId: shipInstitution.referenceId, craftClass: "freight-hauler", issueType: payload.issueType, requiredCapabilities, locationSiteId: "scrap-porch", mobility: "recovered", payerInstitutionId: carrier.id, payer: { balance: carrier.accounts.operating.balance, committed: carrier.accounts.operating.committed ?? 0, protectedCash: carrier.policies?.transportation?.minimumOperatingCash ?? 0 }, servicePrice: 180, wear: payload.wear, issueCount: payload.issueCount, causedByCarefulMode: payload.causedByCarefulMode }, { visible: false });
  }

  function settleRepairInvoice(shipId, amount, referenceId) {
    const hauler = logistics.haulers[shipId];
    if (!hauler || !Number.isFinite(amount) || amount <= 0) return null;
    const transaction = recordAccountTransaction(hauler.carrierInstitutionId, -amount, "repair-expense", referenceId, `Paid Scrap Porch repair invoice ${referenceId}`);
    state.sprc.account.balance += amount;
    // Book the real upkeep cost so this carrier's future freight asks reflect
    // what maintenance now costs it.
    recordServiceCost(state, { institutionId: hauler.carrierInstitutionId, serviceType: "maintenance", price: amount, at: now() });
    publishCarrierEvent("carrier.repairPaid", shipId, { repairOrderId: referenceId, amount, transactionId: transaction.id, balance: transaction.balance }, `${getCarrierContext(shipId).carrierName} paid Scrap Porch ${amount} cr for repairs; operating balance is ${transaction.balance} cr.`);
    return transaction;
  }

  // What the supplying institution charges for the GOODS. Freight is a separate
  // payment to the carrier; this is the sale itself, which previously never
  // happened at all — a source hub simply lost material for nothing.
  //
  // The ask is built from what the material actually cost the seller, so the
  // cost basis recorded when it bought ore propagates into what it resells for.
  function quoteGoods(sellerInstitutionId, commodity, quantity) {
    // Floored at plain market worth. A seller that has not recorded a cost
    // basis yet would otherwise part with material for a single credit.
    const marketUnitValue = getResourceTradeValue(commodity);
    const unitCost = Math.max(getUnitCost(state, sellerInstitutionId, commodity) || 0, marketUnitValue);
    const ask = evaluateSupplierAsk({
      workId: `${quantity} ${commodity}`,
      costComponents: { other: unitCost * quantity },
      traits: getActorTraits(state, sellerInstitutionId),
    });
    return { price: ask.recommendedPrice, unitCost, marketUnitValue, valuation: ask };
  }

  function recordAccountTransaction(institutionId, amount, type, referenceId, description) {
    const institution = logistics.institutions[institutionId];
    institution.accounts ??= {};
    institution.accounts.operating ??= { balance: 0, committed: 0 };
    const account = institution.accounts.operating;
    account.transactions ??= [];
    account.balance = (account.balance ?? 0) + amount;
    const transaction = { id: `TX-${String(++logistics.counters.transaction).padStart(5, "0")}`, at: now(), accountId: account.id ?? `${institutionId}:operating`, institutionId, type, amount, balance: account.balance, referenceId, description };
    account.transactions.push(transaction);
    if (account.transactions.length > 50) account.transactions.splice(0, account.transactions.length - 50);
    return transaction;
  }

  function getCarrierContext(shipId) {
    const hauler = logistics.haulers[shipId] ?? {};
    const carrier = logistics.institutions[hauler.carrierInstitutionId] ?? {};
    const person = logistics.institutions[carrier.controllerInstitutionId] ?? {};
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId] ?? {};
    return { carrierInstitutionId: carrier.id, carrierName: carrier.name ?? carrier.id ?? "Unknown carrier", carrierReferenceId: carrier.referenceId, accountId: carrier.accounts?.operating?.id, pilotInstitutionId: person.id, pilotName: person.name ?? shipId, licenseId: person.license?.id ?? person.referenceId, shipInstitutionId: shipInstitution.id, shipName: shipInstitution.name ?? shipId, shipReferenceId: shipInstitution.referenceId };
  }

  function publishCarrierEvent(type, shipId, payload, message) {
    state.ledger.recordEvent(type, { ...getCarrierContext(shipId), ...payload }, { visible: true, message });
  }

  function publishDecisionOnce(shipId, key, message, payload = {}) {
    const hauler = logistics.haulers[shipId];
    if (!hauler || hauler.lastDecisionKey === key) return;
    hauler.lastDecisionKey = key;
    publishCarrierEvent("carrier.decision", shipId, payload, message);
  }

  function siteName(siteId) { return transportationNetwork.destinations[siteId]?.name ?? SITE_NAMES[siteId] ?? siteId; }
  function formatReason(value) { return String(value).replaceAll("-", " "); }

  function transferCustody(container, institutionId, action, siteId) { container.custodianInstitutionId = institutionId; container.custody.push({ institutionId, action, siteId, at: now() }); }
  // What a carrier can actually load. Prepaid freight draws from goods the
  // buyer already owns and that are sitting at the seller awaiting pickup; only
  // an unpaid run draws from the seller's own stock.
  function availableToLoad(template) {
    const source = logistics.institutions[template.sourceInstitutionId];
    if (!template.prepaid) return source?.inventories?.[template.commodity] ?? 0;
    const held = source?.awaitingPickup?.[template.procurementOrderId];
    return held?.units ?? 0;
  }

  // A carrier that has had every ship committed for a minute buys another, and
  // lays one up after two minutes idle. Ships are never laid up loaded, under
  // tow, or if it would leave the region with none.
  function assessCarrierFleet() {
    logistics.fleetPolicy ??= {};
    const carriers = new Set(Object.values(logistics.haulers).map((hauler) => hauler.carrierInstitutionId));

    carriers.forEach((carrierId) => {
      const carrier = logistics.institutions[carrierId];
      if (!carrier?.accounts?.operating) return;
      const owned = Object.entries(logistics.haulers).filter(([, hauler]) => hauler.carrierInstitutionId === carrierId);
      if (owned.length === 0) return;
      const policy = logistics.fleetPolicy[carrierId] ??= { allBusySince: null };

      const allBusy = owned.every(([, hauler]) => hauler.activeShipmentId || hauler.activeMovementId);
      if (!allBusy) policy.allBusySince = null;
      else policy.allBusySince ??= now();

      const busyLongEnough = policy.allBusySince != null
        && now() - policy.allBusySince >= HAULER_HIRE_AFTER_BUSY_SECONDS * 1000;
      const totalHaulers = Object.keys(logistics.haulers).length;

      if (busyLongEnough && totalHaulers < MAX_HAULERS && commissionHauler) {
        if (carrier.accounts.operating.balance - HAULER_COST < 0) {
          appendHistory("carrier.hireDeferred", { carrierInstitutionId: carrierId, cost: HAULER_COST, balance: Math.round(carrier.accounts.operating.balance) });
        } else if (hireHauler(carrierId, carrier, owned)) {
          policy.allBusySince = null;   // earn the next one from scratch
          return;
        }
      }

      // ── laying one up ─────────────────────────────────────────────────
      if (Object.keys(logistics.haulers).length <= MIN_HAULERS) return;
      owned.forEach(([haulerId, hauler]) => {
        if (hauler.activeShipmentId || hauler.activeMovementId) { hauler.idleSince = null; return; }
        hauler.idleSince ??= now();
        if (now() - hauler.idleSince < HAULER_RELEASE_AFTER_IDLE_SECONDS * 1000) return;
        const ship = shipById.get(haulerId);
        // Never lay up a ship that is carrying something or under tow: the
        // cargo would go with it.
        if (ship?.activeTowRequestId || ship?.cargoTransfers?.length) return;
        if (Object.keys(logistics.haulers).length <= MIN_HAULERS) return;
        layUpHauler(haulerId, hauler, carrierId, carrier);
      });
    });
  }

  function hireHauler(carrierId, carrier, owned) {
    const index = (logistics.counters.hauler = (logistics.counters.hauler ?? 0) + 1);
    const id = `hauler-hired-${index}`;
    const homeSiteId = logistics.haulers[owned[0][0]]?.currentSiteId ?? "yard-exchange";
    const created = commissionHauler({ id, name: `Relief Hauler ${index}`, homeSiteId, seed: 10 + index, carrierInstitutionId: carrier.id });
    if (!created) return false;

    carrier.accounts.operating.balance -= HAULER_COST;
    recordAccountTransaction(carrierId, 0, "capital-expense", id, `Commissioned ${created.name}`);
    const shipInstitutionId = `ship:${id}`;
    logistics.institutions[shipInstitutionId] = {
      id: shipInstitutionId, name: created.name, referenceId: `HAUL-${index}-RELIEF`,
      archetypeId: "cargo-ship", controllerInstitutionId: carrierId, wear: 0, issueCount: 0,
    };
    logistics.haulers[id] = {
      shipInstitutionId, carrierInstitutionId: carrierId, currentSiteId: homeSiteId,
      activeShipmentId: null, activeMovementId: null, maintenanceRequested: false,
      lastDecisionKey: null, status: "seeking-work", idleSince: null,
    };
    shipById.set(id, created);
    appendHistory("carrier.hauerHired", { carrierInstitutionId: carrierId, haulerId: id, cost: HAULER_COST });
    state.ledger.recordEvent("carrier.haulerHired", {
      carrierInstitutionId: carrierId, haulerId: id, shipName: created.name,
      cost: HAULER_COST, fleetSize: Object.keys(logistics.haulers).length,
      balance: Math.round(carrier.accounts.operating.balance),
    }, { visible: true, message: `${carrier.name ?? carrierId} put ${created.name} into service for ${HAULER_COST} cr — every ship it had was committed with freight still waiting.` });
    return true;
  }

  function layUpHauler(haulerId, hauler, carrierId, carrier) {
    const idleSeconds = Math.round((now() - (hauler.idleSince ?? now())) / 1000);
    const ship = shipById.get(haulerId);
    if (ship) ship.isAlive = false;
    shipById.delete(haulerId);
    delete logistics.haulers[haulerId];
    const shipInstitution = logistics.institutions[hauler.shipInstitutionId];
    if (shipInstitution) {
      shipInstitution.status = "retired";
      shipInstitution.retiredAt = now();
    }
    retireDiagnostic(state, haulerId, {
      summary: `Laid up by ${carrier.name ?? carrierId} after ${idleSeconds}s without freight`,
      at: now(),
    });
    decommissionHauler?.(haulerId);
    appendHistory("carrier.haulerLaidUp", { carrierInstitutionId: carrierId, haulerId, idleSeconds });
    state.ledger.recordEvent("carrier.haulerLaidUp", {
      carrierInstitutionId: carrierId, haulerId, idleSeconds,
      fleetSize: Object.keys(logistics.haulers).length,
    }, { visible: true, message: `${carrier.name ?? carrierId} laid up ${haulerId} after ${idleSeconds}s with no freight to carry.` });
  }

  function countActiveForTemplate(templateId) { return Object.values(logistics.shipments).filter((entry) => entry.templateId === templateId && ["assigned", "loaded"].includes(entry.status)).length; }
  function appendHistory(type, payload) { logistics.history.push({ id: `log-history-${logistics.history.length + 1}`, type, at: now(), ...payload }); }
  return { update, assignNpcShipment, acceptPlayerContract, loadPlayerContract, deliverPlayerContract, getState: () => logistics };
}

export function createStandingFreightJob(template, issuer = null, postedRate = null) {
  // The player is offered the rate the carriers are actually being offered. It
  // may have been raised above the opening budget to attract somebody, and
  // quoting the base here would undercut the player against the NPC market.
  const credits = postedRate ?? template.payment;
  return { id: `player-${template.id}`, type: "cargo-run", group: "standing-freight", jobKind: "logistics", repeatable: true, jobTier: "standing", jobTierLabel: "Standing Freight", title: `${template.commodityName} to ${template.destinationName}`, issuer: issuer ?? template.originName, summary: `Load ${template.amount} ${template.commodityName} at ${template.originName} and deliver to ${template.destinationName}.`, terms: { commodity: template.commodity, commodityName: template.commodityName, amount: template.amount, originSiteId: template.originSiteId, originName: template.originName, destinationSiteId: template.destinationSiteId, destinationName: template.destinationName, standingFreightTemplateId: template.id }, reward: { credits }, clauses: ["This is a standing regional freight offer shared with independent and institutional carriers.", "One real container is assigned on acceptance; custody and inventory transfer are recorded.", `Load at ${template.originName} and unload at ${template.destinationName}.`], };
}

// The player sees the same board the carriers do: real runs, backed by real
// purchase orders, and nothing at all where no hub has asked for anything.
export function getStandingFreightJobsForSite(siteId, issuer = null, state = null) {
  if (!state) return [];
  const posted = state.logistics?.postedFreightRates ?? {};
  // Offered at BOTH ends of the lane. An NPC hauler may take a run from the far
  // end and fly to the pickup, so the player sees the same board rather than
  // only what happens to originate where they are standing.
  return getProcurementFreightOffers(state)
    .filter((template) => template.originSiteId === siteId || template.destinationSiteId === siteId)
    .map((template) => createStandingFreightJob(template, issuer, posted[template.id] ?? null));
}
