export const FRONTIER_FREIGHT_CORRIDOR = Object.freeze({
  archetypeId: "frontier-freight-road",
  width: 270,
  endpointWidth: 440,
  waypointSpacing: 250,
  sampleSpacing: 72,
  naturalVariation: 30,
  shoulderDensity: 0.74,
  outerShoulderDensity: 0.38,
  slipstreamSpeedMultiplier: 1.2,
  slipstreamThrustMultiplier: 1.1,
  generator: Object.freeze({
    candidateCount: 24,
    controlPointCount: 10,
    lateralScale: 0.15,
    targetLengthRatio: 1.3,
    minimumLengthRatio: 1.12,
    maximumLengthRatio: 1.42,
    minimumLateralTurns: 3,
    maximumLateralTurns: 7,
    maximumSampleTurn: 0.34,
  }),
  boostPads: Object.freeze({ count: 4, turnCount: 2, turnExitOffset: 0.055, minimumTurnSpacing: 0.2 }),
});
